/*##############################################################################

  THIS IS GENERATED CODE (use C:\SwProjects\_Intern\Arduino\RoomLight_DaylightSimulation\Script\htmlToC_saveFlash.py.ods)
    ==> DO NOT EDIT MANUALLY !!!

##############################################################################*/


/*******************************************************************************
Project   RoomLight

  This is an OpenSource Project.
  You can use, share or improve this project. If you improve this source code
  please share with the comunity or at least with the author of the original
  source code

  Created 22. May 2023 by MarkusNTrains
================================================================================
$HeadURL:  $
$Id:  $
*******************************************************************************/


//-----------------------------------------------------------------------------
// includes
#include "Website.h"


//-----------------------------------------------------------------------------
// This variant needs more heap but less flash
// PROGMEM -> store data in flash
//   to read out the sored data from PROGMEM use one macro of <avr/pgmspace.h>
//   - e.g. (char*)pgm_read_word(&(PARAM_IN_PROGMEM))
//   - or use memcpy_P
//      data_type_t param_SRAM
//      memcpy_P(&param_SRAM, &PARAM_IN_PROGMEM, sizeof(data_type_t))
//   more infos: https://www.arduino.cc/reference/en/language/variables/utilities/progmem/

// F Macro within println (exp.  println(F('Hello World'))) -> store string in flash


const char line1[] PROGMEM = "<!-- html realtime: https://htmledit.squarefree.com/-->";
const char line2[] PROGMEM = "<!DOCTYPE HTML>";
const char line3[] PROGMEM = "<html lang=\"en\">";
const char line4[] PROGMEM = "<head>";
const char line5[] PROGMEM = "<meta charset=\"utf-8\">";
const char line6[] PROGMEM = "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
const char line7[] PROGMEM = "<title>MoBa Room Light</title>";
const char line8[] PROGMEM = "<link rel=\"icon\" href=\"favicon.ico\">";
const char line9[] PROGMEM = "";
const char line10[] PROGMEM = "<style type=\"text/css\">";
const char line11[] PROGMEM = ":root {";
const char line12[] PROGMEM = "--backgroundColor: #222222;";
const char line13[] PROGMEM = "--headerBackgroundColor: #444444;";
const char line14[] PROGMEM = "--BackgroundColorActive: #ffbf00;";
const char line15[] PROGMEM = "--BackgroundColorHover: #ff8000;";
const char line16[] PROGMEM = "--sliderBackgroundColor: #4b4b4b;";
const char line17[] PROGMEM = "--ButtonBackgroundColor: #38a2a7;";
const char line18[] PROGMEM = "--SliderThumbColor: var(--sliderBackgroundColor);";
const char line19[] PROGMEM = "--textColorDark: #000000;";
const char line20[] PROGMEM = "--textColorLight: #ffffff;";
const char line21[] PROGMEM = "--boarderColor: #000000;";
const char line22[] PROGMEM = "";
const char line23[] PROGMEM = "background-color: var(--backgroundColor);";
const char line24[] PROGMEM = "color: var(--textColorLight);";
const char line25[] PROGMEM = "";
const char line26[] PROGMEM = "font-family: Arial, Helvetica, sans-serif;";
const char line27[] PROGMEM = "}";
const char line28[] PROGMEM = ".out_box {";
const char line29[] PROGMEM = "float: left;";
const char line30[] PROGMEM = "margin: 0 20px 20px 0;";
const char line31[] PROGMEM = "border: 1px solid blue;";
const char line32[] PROGMEM = "padding: 0 5px 0 5px;";
const char line33[] PROGMEM = "min-width: 280px;";
const char line34[] PROGMEM = "}";
const char line35[] PROGMEM = "input {";
const char line36[] PROGMEM = "margin: 10px;";
const char line37[] PROGMEM = "}";
const char line38[] PROGMEM = "input {";
const char line39[] PROGMEM = "vertical-align: -3px;";
const char line40[] PROGMEM = "}";
const char line41[] PROGMEM = "h2 {";
const char line42[] PROGMEM = "font-size: 120%;";
const char line43[] PROGMEM = "color: var(--textColorLight);";
const char line44[] PROGMEM = "background-color: var(--headerBackgroundColor);";
const char line45[] PROGMEM = "margin: 5px 0 5px 0;";
const char line46[] PROGMEM = "width: calc(100% - 32px);";
const char line47[] PROGMEM = "border-radius: 4px;";
const char line48[] PROGMEM = "padding: 8px 16px 8px 16px;";
const char line49[] PROGMEM = "border: 2px solid var(--boarderColor);";
const char line50[] PROGMEM = "}";
const char line51[] PROGMEM = "p, form, button {";
const char line52[] PROGMEM = "font-size: 80%;";
const char line53[] PROGMEM = "color: var(--textColorDark);";
const char line54[] PROGMEM = "background-color: var(--backgroundColor);";
const char line55[] PROGMEM = "}";
const char line56[] PROGMEM = "a {";
const char line57[] PROGMEM = "color: var(--BackgroundColorActive);";
const char line58[] PROGMEM = "}";
const char line59[] PROGMEM = "";
const char line60[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line61[] PROGMEM = "/* box */";
const char line62[] PROGMEM = ".box {";
const char line63[] PROGMEM = "background-color: var(--backgroundColor);";
const char line64[] PROGMEM = "width: 100%;";
const char line65[] PROGMEM = "border-radius: 4px;";
const char line66[] PROGMEM = "/*border: 2px solid var(--boarderColor);\t\t\t*/";
const char line67[] PROGMEM = "}";
const char line68[] PROGMEM = ".box_header {";
const char line69[] PROGMEM = "font-size: 125%;";
const char line70[] PROGMEM = "font-weight: bold;";
const char line71[] PROGMEM = "color: var(--textColorLight);";
const char line72[] PROGMEM = "background-color: var(--headerBackgroundColor);";
const char line73[] PROGMEM = "margin: 0 0 10px 0;";
const char line74[] PROGMEM = "width: calc(100% - 32px);";
const char line75[] PROGMEM = "padding: 8px 16px 8px 16px;";
const char line76[] PROGMEM = "}";
const char line77[] PROGMEM = ".box_content {";
const char line78[] PROGMEM = "padding: 8px 8px 8px 8px;";
const char line79[] PROGMEM = "}";
const char line80[] PROGMEM = "";
const char line81[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line82[] PROGMEM = "/* button */";
const char line83[] PROGMEM = ".button {";
const char line84[] PROGMEM = "color: var(--textColorDark);";
const char line85[] PROGMEM = "background-color: var(--ButtonBackgroundColor);";
const char line86[] PROGMEM = "/*border: 2px solid var(--headerBackgroundColor);*/";
const char line87[] PROGMEM = "border-radius: 4px;";
const char line88[] PROGMEM = "padding: 16px 12px;";
const char line89[] PROGMEM = "text-align: center;";
const char line90[] PROGMEM = "/*text-decoration: none;*/";
const char line91[] PROGMEM = "display: inline-block;";
const char line92[] PROGMEM = "font-size: 16px;";
const char line93[] PROGMEM = "margin: 4px 2px;";
const char line94[] PROGMEM = "-webkit-transition-duration: 0.4s; /* Safari */";
const char line95[] PROGMEM = "transition-duration: 0.4s;";
const char line96[] PROGMEM = "cursor: pointer;";
const char line97[] PROGMEM = "}";
const char line98[] PROGMEM = "";
const char line99[] PROGMEM = ".button:hover {";
const char line100[] PROGMEM = "background-color: var(--BackgroundColorHover);";
const char line101[] PROGMEM = "color: var(--textColorDark);";
const char line102[] PROGMEM = "}";
const char line103[] PROGMEM = ".button:active {";
const char line104[] PROGMEM = "background-color: var(--BackgroundColorActive);";
const char line105[] PROGMEM = "color: var(--textColorDark);";
const char line106[] PROGMEM = "transform: translateY(2px);";
const char line107[] PROGMEM = "}";
const char line108[] PROGMEM = ".active-class {";
const char line109[] PROGMEM = "background-color: var(--BackgroundColorActive);";
const char line110[] PROGMEM = "color: var(--textColorDark);";
const char line111[] PROGMEM = "}";
const char line112[] PROGMEM = "";
const char line113[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line114[] PROGMEM = "/* user values */";
const char line115[] PROGMEM = ".user_value {";
const char line116[] PROGMEM = "border: 0;";
const char line117[] PROGMEM = "color: #f6931f;";
const char line118[] PROGMEM = "font-weight: bold;";
const char line119[] PROGMEM = "}";
const char line120[] PROGMEM = "";
const char line121[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line122[] PROGMEM = "/* slider */";
const char line123[] PROGMEM = ".slidecontainer {";
const char line124[] PROGMEM = "width: 100%;";
const char line125[] PROGMEM = "}";
const char line126[] PROGMEM = "";
const char line127[] PROGMEM = ".slider {";
const char line128[] PROGMEM = "-webkit-appearance: none;";
const char line129[] PROGMEM = "-moz-appearance: none;";
const char line130[] PROGMEM = "width: calc(100% - 15px);";
const char line131[] PROGMEM = "height: 15px;";
const char line132[] PROGMEM = "border: 1px solid var(--headerBackgroundColor);";
const char line133[] PROGMEM = "border-radius: 5px;";
const char line134[] PROGMEM = "background: var(--BackgroundColorActive);";
const char line135[] PROGMEM = "outline: none;";
const char line136[] PROGMEM = "opacity: 1;";
const char line137[] PROGMEM = "-webkit-transition: .2s;";
const char line138[] PROGMEM = "transition: opacity .2s;";
const char line139[] PROGMEM = "}";
const char line140[] PROGMEM = "";
const char line141[] PROGMEM = ".slider::-webkit-slider-thumb {";
const char line142[] PROGMEM = "-webkit-appearance: none;";
const char line143[] PROGMEM = "-moz-appearance: none;";
const char line144[] PROGMEM = "appearance: none;";
const char line145[] PROGMEM = "width: 25px;";
const char line146[] PROGMEM = "height: 25px;";
const char line147[] PROGMEM = "border-radius: 50%;";
const char line148[] PROGMEM = "background: var(--SliderThumbColor);";
const char line149[] PROGMEM = "cursor: pointer;";
const char line150[] PROGMEM = "}";
const char line151[] PROGMEM = "";
const char line152[] PROGMEM = ".slider::-moz-range-thumb {";
const char line153[] PROGMEM = "width: 25px;";
const char line154[] PROGMEM = "height: 25px;";
const char line155[] PROGMEM = "border-radius: 50%;";
const char line156[] PROGMEM = "background: var(--SliderThumbColor);";
const char line157[] PROGMEM = "cursor: pointer;";
const char line158[] PROGMEM = "}";
const char line159[] PROGMEM = "";
const char line160[] PROGMEM = "";
const char line161[] PROGMEM = "/*---------------------------------------------------------------------*/";
const char line162[] PROGMEM = "/* 2 thumb slider */";
const char line163[] PROGMEM = "#led_slider_row {";
const char line164[] PROGMEM = "width: 150px;";
const char line165[] PROGMEM = "}";
const char line166[] PROGMEM = "";
const char line167[] PROGMEM = "#led_slider_column {";
const char line168[] PROGMEM = "width: calc(100% - 150px);";
const char line169[] PROGMEM = "}";
const char line170[] PROGMEM = "";
const char line171[] PROGMEM = ".wrap {";
const char line172[] PROGMEM = "--dif: calc(var(--max) - var(--min));";
const char line173[] PROGMEM = "display: grid;";
const char line174[] PROGMEM = "grid-template: repeat(2, max-content) 2em/1fr 1fr;";
const char line175[] PROGMEM = "overflow: hidden;";
const char line176[] PROGMEM = "position: relative;";
const char line177[] PROGMEM = "margin: 1em auto;";
const char line178[] PROGMEM = "width: 100%;";
const char line179[] PROGMEM = "background: linear-gradient(0deg, var(--sliderBackgroundColor) 2em, transparent 0);";
const char line180[] PROGMEM = "font-family: ubuntu mono, consolas, monaco, monospace;";
const char line181[] PROGMEM = "/*border: 1px solid;*/";
const char line182[] PROGMEM = "border-color: var(--sliderBackgroundColor);";
const char line183[] PROGMEM = "border-radius: 10px;";
const char line184[] PROGMEM = "}";
const char line185[] PROGMEM = ".wrap::before, .wrap::after {";
const char line186[] PROGMEM = "grid-column: 1/span 2;";
const char line187[] PROGMEM = "grid-row: 3;";
const char line188[] PROGMEM = "height: 100%;";
const char line189[] PROGMEM = "background: var(--BackgroundColorActive);";
const char line190[] PROGMEM = "content: \"\";";
const char line191[] PROGMEM = "}";
const char line192[] PROGMEM = ".wrap::before {";
const char line193[] PROGMEM = "margin-left: calc((var(--a) - var(--min))/var(--dif)*100%);";
const char line194[] PROGMEM = "width: calc((var(--b) - var(--a))/var(--dif)*100%);";
const char line195[] PROGMEM = "}";
const char line196[] PROGMEM = ".wrap::after {";
const char line197[] PROGMEM = "margin-left: calc((var(--b) - var(--min))/var(--dif)*100%);";
const char line198[] PROGMEM = "width: calc((var(--a) - var(--b))/var(--dif)*100%);";
const char line199[] PROGMEM = "}";
const char line200[] PROGMEM = "";
const char line201[] PROGMEM = "[id=multi-lbl] {";
const char line202[] PROGMEM = "grid-column: 1/span 2;";
const char line203[] PROGMEM = "}";
const char line204[] PROGMEM = "";
const char line205[] PROGMEM = ".sr-only {";
const char line206[] PROGMEM = "position: absolute;";
const char line207[] PROGMEM = "clip-path: inset(50%);";
const char line208[] PROGMEM = "}";
const char line209[] PROGMEM = "";
const char line210[] PROGMEM = "input.twoThumbSlider[type=range] {";
const char line211[] PROGMEM = "grid-column: 1/span 2;";
const char line212[] PROGMEM = "grid-row: 3;";
const char line213[] PROGMEM = "z-index: 1;";
const char line214[] PROGMEM = "top: 0;";
const char line215[] PROGMEM = "left: 0;";
const char line216[] PROGMEM = "margin: 0;";
const char line217[] PROGMEM = "background: none;";
const char line218[] PROGMEM = "/* get rid of white Chrome background */";
const char line219[] PROGMEM = "color: var(--SliderThumbColor);";
const char line220[] PROGMEM = "pointer-events: none;";
const char line221[] PROGMEM = "}";
const char line222[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-runnable-track, input[type=range]::-webkit-slider-thumb, input[type=range] {";
const char line223[] PROGMEM = "-webkit-appearance: none;";
const char line224[] PROGMEM = "}";
const char line225[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-runnable-track {";
const char line226[] PROGMEM = "width: 100%;";
const char line227[] PROGMEM = "height: 100%;";
const char line228[] PROGMEM = "background: none;";
const char line229[] PROGMEM = "}";
const char line230[] PROGMEM = "input.twoThumbSlider[type=range]::-moz-range-track {";
const char line231[] PROGMEM = "width: 100%;";
const char line232[] PROGMEM = "height: 100%;";
const char line233[] PROGMEM = "background: none;";
const char line234[] PROGMEM = "}";
const char line235[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-thumb {";
const char line236[] PROGMEM = "border: 1px solid var(--backgroundColor);";
const char line237[] PROGMEM = "/* get rid of Chrom thumb border */";
const char line238[] PROGMEM = "width: 2em;";
const char line239[] PROGMEM = "height: 100%;";
const char line240[] PROGMEM = "border-radius: 0;";
const char line241[] PROGMEM = "/* get rid of Chrome corner rounding */";
const char line242[] PROGMEM = "background: currentcolor;";
const char line243[] PROGMEM = "pointer-events: auto;";
const char line244[] PROGMEM = "}";
const char line245[] PROGMEM = "input.twoThumbSlider[type=range]::-moz-range-thumb {";
const char line246[] PROGMEM = "border: 1px solid var(--backgroundColor);";
const char line247[] PROGMEM = "/* get rid of Firefox thumb border */";
const char line248[] PROGMEM = "width: 2em;";
const char line249[] PROGMEM = "height: 100%;";
const char line250[] PROGMEM = "border-radius: 0;";
const char line251[] PROGMEM = "/* get rid of Firefox corner rounding */";
const char line252[] PROGMEM = "background: currentcolor;";
const char line253[] PROGMEM = "pointer-events: auto;";
const char line254[] PROGMEM = "}";
const char line255[] PROGMEM = "input.twoThumbSlider[type=range]:focus {";
const char line256[] PROGMEM = "z-index: 2;";
const char line257[] PROGMEM = "outline: dotted 1px currentcolor;";
const char line258[] PROGMEM = "}";
const char line259[] PROGMEM = "input.twoThumbSlider[type=range]:focus, input[type=range]:focus + output {";
const char line260[] PROGMEM = "color: darkorange;";
const char line261[] PROGMEM = "}";
const char line262[] PROGMEM = "";
const char line263[] PROGMEM = "output.twoThumbSlider {";
const char line264[] PROGMEM = "grid-row: 2;";
const char line265[] PROGMEM = "}";
const char line266[] PROGMEM = "output.twoThumbSlider:last-child {";
const char line267[] PROGMEM = "text-align: right;";
const char line268[] PROGMEM = "}";
const char line269[] PROGMEM = "output.twoThumbSlider::after {";
const char line270[] PROGMEM = "counter-reset: c var(--c);";
const char line271[] PROGMEM = "content: \"--\" attr(for) \": \" counter(c) \";\";";
const char line272[] PROGMEM = "}";
const char line273[] PROGMEM = "";
const char line274[] PROGMEM = "</style>";
const char line275[] PROGMEM = "";
const char line276[] PROGMEM = "";
const char line277[] PROGMEM = "<script type=\"text/javascript\" charset=\"utf-8\">";
const char line278[] PROGMEM = "//--- const ------------------------------------------------------";
const char line279[] PROGMEM = "//--- Firmware version";
const char line280[] PROGMEM = "const GLOBAL_WebserverVersion_Major = 1;";
const char line281[] PROGMEM = "const GLOBAL_WebserverVersion_Minor = 6;";
const char line282[] PROGMEM = "";
const char line283[] PROGMEM = "";
const char line284[] PROGMEM = "const LIGHT_SCENE =";
const char line285[] PROGMEM = "{";
const char line286[] PROGMEM = "OfficeTable: 0,";
const char line287[] PROGMEM = "LightOn: 1,";
const char line288[] PROGMEM = "Rainbow: 2,";
const char line289[] PROGMEM = "Sunset: 3,";
const char line290[] PROGMEM = "Sunrise: 4,";
const char line291[] PROGMEM = "PowerOff: 5,";
const char line292[] PROGMEM = "Disco: 6,";
const char line293[] PROGMEM = "Sbh: 7,";
const char line294[] PROGMEM = "UserSetting: 8,";
const char line295[] PROGMEM = "IDLE: 9,";
const char line296[] PROGMEM = "Lightning: 10,";
const char line297[] PROGMEM = "Moba: 11,";
const char line298[] PROGMEM = "Day: 12,";
const char line299[] PROGMEM = "Night: 13,";
const char line300[] PROGMEM = "Cloud: 14,";
const char line301[] PROGMEM = "NOF: 15";
const char line302[] PROGMEM = "};";
const char line303[] PROGMEM = "";
const char line304[] PROGMEM = "const XML_RREQUEST =";
const char line305[] PROGMEM = "{";
const char line306[] PROGMEM = "GetCurrentData: \"GetCurrentData\",";
const char line307[] PROGMEM = "GetInfo: \"GetInfo\",";
const char line308[] PROGMEM = "SetArea: \"SetArea\",";
const char line309[] PROGMEM = "SetBrightness: \"SetBrightness\",";
const char line310[] PROGMEM = "SetColor: \"SetColor\",";
const char line311[] PROGMEM = "SetLightScene: \"LightScene\",";
const char line312[] PROGMEM = "};";
const char line313[] PROGMEM = "";
const char line314[] PROGMEM = "const FIND_SERVER_TIMEOUT_MS = 2000;";
const char line315[] PROGMEM = "const REQUEST_CURRENT_DATA_FROM_SERVER_TIMEOUT_MS = 3000;";
const char line316[] PROGMEM = "const SERVER_RESPONSE_TIMEOUT_MS = 2500;  // must be shorter than REQUEST_CURRENT_DATA_FROM_ARDUINO_TIMEOUT_MS";
const char line317[] PROGMEM = "const USER_SETTING_OFFSET = 1;";
const char line318[] PROGMEM = "";
const char line319[] PROGMEM = "";
const char line320[] PROGMEM = "//--- static variables --------------------------------------------";
const char line321[] PROGMEM = "var s_lock_send_data = false;";
const char line322[] PROGMEM = "var s_is_send_data_pending = false;";
const char line323[] PROGMEM = "var s_pending_xml_request = \"\";";
const char line324[] PROGMEM = "var s_sendToServer_timeoutTimer = null;";
const char line325[] PROGMEM = "var s_requestDataFromServer_intervalTimer = null;";
const char line326[] PROGMEM = "var s_findServer_intervalTimer = null;";
const char line327[] PROGMEM = "var s_is_server_connected = true;";
const char line328[] PROGMEM = "var s_xhttp = null;";
const char line329[] PROGMEM = "";
const char line330[] PROGMEM = "";
const char line331[] PROGMEM = "//--- function prototypes -----------------------------------------";
const char line332[] PROGMEM = "";
const char line333[] PROGMEM = "";
const char line334[] PROGMEM = "//--- function ----------------------------------------------------";
const char line335[] PROGMEM = "function SendDataToServer(xml_request)";
const char line336[] PROGMEM = "{";
const char line337[] PROGMEM = "if (s_lock_send_data == false)";
const char line338[] PROGMEM = "{";
const char line339[] PROGMEM = "s_lock_send_data = true;";
const char line340[] PROGMEM = "Reset_RequestCurrentDataFromServer_IntervallTimer();";
const char line341[] PROGMEM = "nocache = \"&nocache=\" + Math.random() * 1000000;";
const char line342[] PROGMEM = "";
const char line343[] PROGMEM = "if (s_xhttp != null)";
const char line344[] PROGMEM = "{";
const char line345[] PROGMEM = "s_xhttp.abort();";
const char line346[] PROGMEM = "s_xhttp = null;";
const char line347[] PROGMEM = "}";
const char line348[] PROGMEM = "";
const char line349[] PROGMEM = "s_xhttp = new XMLHttpRequest();";
const char line350[] PROGMEM = "s_xhttp.timeout = SERVER_RESPONSE_TIMEOUT_MS;";
const char line351[] PROGMEM = "s_xhttp.ontimeout = function()";
const char line352[] PROGMEM = "{";
const char line353[] PROGMEM = "s_is_server_connected = false;";
const char line354[] PROGMEM = "clearInterval(s_requestDataFromServer_intervalTimer);";
const char line355[] PROGMEM = "";
const char line356[] PROGMEM = "document.body.style.cursor = \"progress\";";
const char line357[] PROGMEM = "";
const char line358[] PROGMEM = "LightScene_SetAllAsInactive();";
const char line359[] PROGMEM = "";
const char line360[] PROGMEM = "document.getElementById(\"brightness_value\").innerHTML = (\"loading...\");";
const char line361[] PROGMEM = "document.getElementById(\"color_rgb_value\").innerHTML = (\"loading...\");";
const char line362[] PROGMEM = "document.getElementById(\"color_red_value\").innerHTML = (\"loading...\");";
const char line363[] PROGMEM = "document.getElementById(\"color_green_value\").innerHTML = (\"loading...\");";
const char line364[] PROGMEM = "document.getElementById(\"color_blue_value\").innerHTML = (\"loading...\");";
const char line365[] PROGMEM = "document.getElementById(\"color_white_value\").innerHTML = (\"loading...\");";
const char line366[] PROGMEM = "document.getElementById(\"led_column\").innerHTML = (\"loading...\");";
const char line367[] PROGMEM = "document.getElementById(\"led_row\").innerHTML = (\"loading...\");";
const char line368[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#3F3F3F');";
const char line369[] PROGMEM = "";
const char line370[] PROGMEM = "document.getElementById(\"footer_version\").innerHTML = (\"v\" + GLOBAL_WebserverVersion_Major + \".\" + GLOBAL_WebserverVersion_Minor);";
const char line371[] PROGMEM = "";
const char line372[] PROGMEM = "FindServer();";
const char line373[] PROGMEM = "}";
const char line374[] PROGMEM = "s_xhttp.onreadystatechange = function()";
const char line375[] PROGMEM = "{";
const char line376[] PROGMEM = "if (this.readyState == XMLHttpRequest.DONE)";
const char line377[] PROGMEM = "{";
const char line378[] PROGMEM = "if (this.status == 200)";
const char line379[] PROGMEM = "{";
const char line380[] PROGMEM = "if (this.responseXML != null)";
const char line381[] PROGMEM = "{";
const char line382[] PROGMEM = "// XML file received from Server";
const char line383[] PROGMEM = "if (s_is_server_connected == false)";
const char line384[] PROGMEM = "{";
const char line385[] PROGMEM = "s_is_server_connected = true;";
const char line386[] PROGMEM = "document.body.style.cursor = \"default\";";
const char line387[] PROGMEM = "clearInterval(s_findServer_intervalTimer);";
const char line388[] PROGMEM = "RequestCurrentDataFromServer();";
const char line389[] PROGMEM = "}";
const char line390[] PROGMEM = "";
const char line391[] PROGMEM = "var re = this.responseXML.getElementsByTagName('info');";
const char line392[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line393[] PROGMEM = "{";
const char line394[] PROGMEM = "var version_major = this.responseXML.getElementsByTagName('major')[0].childNodes[0].nodeValue;";
const char line395[] PROGMEM = "var version_minor = this.responseXML.getElementsByTagName('minor')[0].childNodes[0].nodeValue;";
const char line396[] PROGMEM = "var led_nof_row = parseInt(this.responseXML.getElementsByTagName('nof_row')[0].childNodes[0].nodeValue);";
const char line397[] PROGMEM = "var led_nof_px = parseInt(this.responseXML.getElementsByTagName('nof_leds')[0].childNodes[0].nodeValue);";
const char line398[] PROGMEM = "var xs = parseInt(this.responseXML.getElementsByTagName('xs')[0].childNodes[0].nodeValue);";
const char line399[] PROGMEM = "var xe = parseInt(this.responseXML.getElementsByTagName('xe')[0].childNodes[0].nodeValue);";
const char line400[] PROGMEM = "var ys = parseInt(this.responseXML.getElementsByTagName('ys')[0].childNodes[0].nodeValue);";
const char line401[] PROGMEM = "var ye = parseInt(this.responseXML.getElementsByTagName('ye')[0].childNodes[0].nodeValue);";
const char line402[] PROGMEM = "";
const char line403[] PROGMEM = "";
const char line404[] PROGMEM = "//--- update user setting columen and row slider --------------------------------";
const char line405[] PROGMEM = "//<!--<div style=\"transform: rotate(270deg);\">-->";
const char line406[] PROGMEM = "//<div id=\"slider_row\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: 0; --b: 5; --min: 0; --max: 5;\">";
const char line407[] PROGMEM = "//    <!--<div id=\"multi-lbl\">Multi thumb slider: 0 - 15</div>-->";
const char line408[] PROGMEM = "//    <input id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"0\" max=\"5\" />";
const char line409[] PROGMEM = "//    <!--<output for=\"a\" style=\"--c: var(--a)\"></output>-->";
const char line410[] PROGMEM = "//    <input id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"5\" max=\"5\" />";
const char line411[] PROGMEM = "//    <!--<output for=\"b\" style=\"--c: var(--b)\"></output>-->";
const char line412[] PROGMEM = "//</div>";
const char line413[] PROGMEM = "var slider_row_max = led_nof_row - USER_SETTING_OFFSET;";
const char line414[] PROGMEM = "document.getElementById(\"led_slider_row\").innerHTML = (";
const char line415[] PROGMEM = "'<div id=\"slider_row\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: ' + ys + '; --b: ' + ye + '; --min: 0; --max: ' + slider_row_max + ';\">'";
const char line416[] PROGMEM = "+   '<input name=\"ledSliderRow_a\" id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"' + ys + '\" max=\"' + slider_row_max + '\" />'";
const char line417[] PROGMEM = "+   '<input name=\"ledSliderRow_b\" id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"' + ye + '\" max=\"' + slider_row_max + '\" />'";
const char line418[] PROGMEM = "+ '</div>'";
const char line419[] PROGMEM = ");";
const char line420[] PROGMEM = "if (led_nof_row > 1)";
const char line421[] PROGMEM = "{";
const char line422[] PROGMEM = "document.getElementById(\"led_slider_row\").style.visibility = 'visible';";
const char line423[] PROGMEM = "}";
const char line424[] PROGMEM = "else";
const char line425[] PROGMEM = "{";
const char line426[] PROGMEM = "document.getElementById(\"led_slider_row\").style.visibility = 'hidden';";
const char line427[] PROGMEM = "}";
const char line428[] PROGMEM = "";
const char line429[] PROGMEM = "//<div id=\"slider_columen\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: 20; --b: 120; --min: 0; --max: 239\">";
const char line430[] PROGMEM = "//    <!--<div id=\"multi-lbl\">Multi thumb slider: 0 - 15</div>-->";
const char line431[] PROGMEM = "//    <input id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"20\" max=\"239\" />";
const char line432[] PROGMEM = "//    <!--<output for=\"a\" style=\"--c: var(--a)\"></output>-->";
const char line433[] PROGMEM = "//    <input id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"120\" max=\"239\" />";
const char line434[] PROGMEM = "//    <!--<output for=\"b\" style=\"--c: var(--b)\"></output>-->";
const char line435[] PROGMEM = "//</div>";
const char line436[] PROGMEM = "var slider_column_max = led_nof_px - USER_SETTING_OFFSET;";
const char line437[] PROGMEM = "document.getElementById(\"led_slider_column\").innerHTML = (";
const char line438[] PROGMEM = "'<div id=\"slider_columen\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: ' + xs + '; --b: ' + xe + '; --min: 0; --max: ' + slider_column_max + '\">'";
const char line439[] PROGMEM = "+   '<input name=\"ledSliderColumn_a\" id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"' + xs + '\" max=\"' + slider_column_max + '\" />'";
const char line440[] PROGMEM = "+   '<input name=\"ledSliderColumn_b\" id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"' + xe + '\" max=\"' + slider_column_max + '\" />'";
const char line441[] PROGMEM = "+ '</div>'";
const char line442[] PROGMEM = ");";
const char line443[] PROGMEM = "";
const char line444[] PROGMEM = "//--- display Arduino room light firmware version in footer ---------------------";
const char line445[] PROGMEM = "document.getElementById(\"footer_version\").innerHTML = (\"v\" + version_major + \".\" + version_minor);";
const char line446[] PROGMEM = "if ((version_major != GLOBAL_WebserverVersion_Major) || (version_minor != GLOBAL_WebserverVersion_Minor))";
const char line447[] PROGMEM = "{";
const char line448[] PROGMEM = "location.reload();";
const char line449[] PROGMEM = "}";
const char line450[] PROGMEM = "}";
const char line451[] PROGMEM = "";
const char line452[] PROGMEM = "re = this.responseXML.getElementsByTagName('scene');";
const char line453[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line454[] PROGMEM = "{";
const char line455[] PROGMEM = "LightScene_ShowAsActive(re[0].childNodes[0].nodeValue);";
const char line456[] PROGMEM = "}";
const char line457[] PROGMEM = "";
const char line458[] PROGMEM = "re = this.responseXML.getElementsByTagName('brightness');";
const char line459[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line460[] PROGMEM = "{";
const char line461[] PROGMEM = "document.getElementById(\"brightness_slider\").value = re[0].childNodes[0].nodeValue;";
const char line462[] PROGMEM = "document.getElementById(\"brightness_value\").innerHTML = re[0].childNodes[0].nodeValue;";
const char line463[] PROGMEM = "}";
const char line464[] PROGMEM = "";
const char line465[] PROGMEM = "re = this.responseXML.getElementsByTagName('color');";
const char line466[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line467[] PROGMEM = "{";
const char line468[] PROGMEM = "var color = parseInt(re[0].childNodes[0].nodeValue);";
const char line469[] PROGMEM = "if (color > 0xFFFFFF)";
const char line470[] PROGMEM = "{";
const char line471[] PROGMEM = "var white = (color >> 24) & 0xFF;";
const char line472[] PROGMEM = "document.getElementById(\"color_white_slider\").value = white;";
const char line473[] PROGMEM = "document.getElementById(\"color_white_value\").innerHTML = white;";
const char line474[] PROGMEM = "colorStr = ('000000' + ((white << 16) | (white << 8) | white).toString(16)).slice(-6);";
const char line475[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line476[] PROGMEM = "}";
const char line477[] PROGMEM = "else";
const char line478[] PROGMEM = "{";
const char line479[] PROGMEM = "var slider_value = 0;";
const char line480[] PROGMEM = "if (((color >= 0xFF0000) && (color <= 0xFFFF00)) && (((color & 0xFF0000) == 0xFF0000) && (((color & 0xFF) == 0x0))))";
const char line481[] PROGMEM = "{";
const char line482[] PROGMEM = "slider_value = ((color & 0xFF00) >> 8);";
const char line483[] PROGMEM = "}";
const char line484[] PROGMEM = "else if (((color >= 0x00FF00) && (color <= 0xFFFF00)) && (((color & 0xFF00) == 0xFF00) && (((color & 0xFF) == 0x0))))";
const char line485[] PROGMEM = "{";
const char line486[] PROGMEM = "slider_value = 511 - ((color & 0xFF0000) >> 16);";
const char line487[] PROGMEM = "}";
const char line488[] PROGMEM = "else if (((color >= 0x00FF00) && (color <= 0x00FFFF)) && (((color & 0xFF00) == 0xFF00) && (((color & 0xFF0000) == 0x0))))";
const char line489[] PROGMEM = "{";
const char line490[] PROGMEM = "slider_value = 512 + (color & 0xFF);";
const char line491[] PROGMEM = "}";
const char line492[] PROGMEM = "else if (((color >= 0x0000FF) && (color <= 0x00FFFF)) && (((color & 0xFF) == 0xFF) && (((color & 0xFF0000) == 0x0))))";
const char line493[] PROGMEM = "{";
const char line494[] PROGMEM = "slider_value = 1023 - ((color & 0x00FF00) >> 8);";
const char line495[] PROGMEM = "}";
const char line496[] PROGMEM = "else if (((color >= 0x0000FF) && (color <= 0xFF00FF)) && (((color & 0xFF) == 0xFF) && (((color & 0xFF00) == 0x0))))";
const char line497[] PROGMEM = "{";
const char line498[] PROGMEM = "slider_value = 1024 + ((color & 0xFF0000) >> 16);";
const char line499[] PROGMEM = "}";
const char line500[] PROGMEM = "else if (((color >= 0xFF0000) && (color <= 0xFF00FF)) && (((color & 0xFF0000) == 0xFF0000) && (((color & 0xFF00) == 0x0))))";
const char line501[] PROGMEM = "{";
const char line502[] PROGMEM = "slider_value = 1535 - (color & 0xFF);";
const char line503[] PROGMEM = "}";
const char line504[] PROGMEM = "";
const char line505[] PROGMEM = "// set rgb combined slider";
const char line506[] PROGMEM = "var colorStr = ('000000' + color.toString(16)).slice(-6);";
const char line507[] PROGMEM = "document.getElementById(\"color_rgb_slider\").value = slider_value;";
const char line508[] PROGMEM = "document.getElementById(\"color_rgb_value\").innerHTML = '0x' + colorStr;";
const char line509[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line510[] PROGMEM = "}";
const char line511[] PROGMEM = "";
const char line512[] PROGMEM = "// set rgb single slider";
const char line513[] PROGMEM = "var red = (color >> 16) & 0xFF;";
const char line514[] PROGMEM = "var green = (color >> 8) & 0xFF;";
const char line515[] PROGMEM = "var blue = color & 0xFF;";
const char line516[] PROGMEM = "document.getElementById(\"color_red_value\").innerHTML = red;";
const char line517[] PROGMEM = "document.getElementById(\"color_green_value\").innerHTML = green;";
const char line518[] PROGMEM = "document.getElementById(\"color_blue_value\").innerHTML = blue;";
const char line519[] PROGMEM = "document.getElementById(\"color_red_slider\").value = red;";
const char line520[] PROGMEM = "document.getElementById(\"color_green_slider\").value = green;";
const char line521[] PROGMEM = "document.getElementById(\"color_blue_slider\").value = blue;";
const char line522[] PROGMEM = "}";
const char line523[] PROGMEM = "";
const char line524[] PROGMEM = "re = this.responseXML.getElementsByTagName('led_area');";
const char line525[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line526[] PROGMEM = "{";
const char line527[] PROGMEM = "var xs = parseInt(this.responseXML.getElementsByTagName('xs')[0].childNodes[0].nodeValue);";
const char line528[] PROGMEM = "var xe = parseInt(this.responseXML.getElementsByTagName('xe')[0].childNodes[0].nodeValue);";
const char line529[] PROGMEM = "var ys = parseInt(this.responseXML.getElementsByTagName('ys')[0].childNodes[0].nodeValue);";
const char line530[] PROGMEM = "var ye = parseInt(this.responseXML.getElementsByTagName('ye')[0].childNodes[0].nodeValue);";
const char line531[] PROGMEM = "";
const char line532[] PROGMEM = "document.getElementById(\"led_row\").innerHTML = ((ys + USER_SETTING_OFFSET) + \" - \" + (ye + USER_SETTING_OFFSET));";
const char line533[] PROGMEM = "document.getElementById(\"slider_row\").style.setProperty(\"--a\", ys);";
const char line534[] PROGMEM = "document.getElementById(\"slider_row\").style.setProperty(\"--b\", ye);";
const char line535[] PROGMEM = "document.getElementsByName(\"ledSliderRow_a\")[0].value = ys;";
const char line536[] PROGMEM = "document.getElementsByName(\"ledSliderRow_b\")[0].value = ye;";
const char line537[] PROGMEM = "";
const char line538[] PROGMEM = "document.getElementById(\"led_column\").innerHTML = ((xs + USER_SETTING_OFFSET) + \" - \" + (xe + USER_SETTING_OFFSET));";
const char line539[] PROGMEM = "document.getElementById(\"slider_columen\").style.setProperty(\"--a\", xs);";
const char line540[] PROGMEM = "document.getElementById(\"slider_columen\").style.setProperty(\"--b\", xe);";
const char line541[] PROGMEM = "document.getElementsByName(\"ledSliderColumn_a\")[0].value = xs;";
const char line542[] PROGMEM = "document.getElementsByName(\"ledSliderColumn_b\")[0].value = xe;";
const char line543[] PROGMEM = "}";
const char line544[] PROGMEM = "";
const char line545[] PROGMEM = "";
const char line546[] PROGMEM = "if (s_sendToServer_timeoutTimer != null)";
const char line547[] PROGMEM = "{";
const char line548[] PROGMEM = "clearTimeout(s_sendToServer_timeoutTimer);";
const char line549[] PROGMEM = "ReleaseLock();";
const char line550[] PROGMEM = "}";
const char line551[] PROGMEM = "}";
const char line552[] PROGMEM = "else";
const char line553[] PROGMEM = "{";
const char line554[] PROGMEM = "alert(\"XML = NULL\");";
const char line555[] PROGMEM = "}";
const char line556[] PROGMEM = "}";
const char line557[] PROGMEM = "else";
const char line558[] PROGMEM = "{";
const char line559[] PROGMEM = "//alert(\"Keine Verbindung zum Webserver\\nStatus: \" + this.status);";
const char line560[] PROGMEM = "}";
const char line561[] PROGMEM = "}";
const char line562[] PROGMEM = "}";
const char line563[] PROGMEM = "";
const char line564[] PROGMEM = "// send HTTP GET request with data";
const char line565[] PROGMEM = "s_xhttp.open(\"GET\", \"ajax_inputs\" + xml_request + nocache, true);";
const char line566[] PROGMEM = "s_xhttp.send();";
const char line567[] PROGMEM = "";
const char line568[] PROGMEM = "// lock Send to Arduino";
const char line569[] PROGMEM = "s_sendToServer_timeoutTimer = setTimeout('ReleaseLock()', REQUEST_CURRENT_DATA_FROM_SERVER_TIMEOUT_MS);";
const char line570[] PROGMEM = "}";
const char line571[] PROGMEM = "else";
const char line572[] PROGMEM = "{";
const char line573[] PROGMEM = "s_is_send_data_pending = true;";
const char line574[] PROGMEM = "s_pending_xml_request = xml_request;";
const char line575[] PROGMEM = "}";
const char line576[] PROGMEM = "}";
const char line577[] PROGMEM = "";
const char line578[] PROGMEM = "function SendDataToServerWhenConnected(xml_request)";
const char line579[] PROGMEM = "{";
const char line580[] PROGMEM = "if (s_is_server_connected == true)";
const char line581[] PROGMEM = "{";
const char line582[] PROGMEM = "SendDataToServer(xml_request);";
const char line583[] PROGMEM = "}";
const char line584[] PROGMEM = "}";
const char line585[] PROGMEM = "";
const char line586[] PROGMEM = "function RequestCurrentDataFromServer()";
const char line587[] PROGMEM = "{";
const char line588[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.GetCurrentData);";
const char line589[] PROGMEM = "}";
const char line590[] PROGMEM = "";
const char line591[] PROGMEM = "function FindServer()";
const char line592[] PROGMEM = "{";
const char line593[] PROGMEM = "s_is_server_connected = false;";
const char line594[] PROGMEM = "clearInterval(s_findServer_intervalTimer);";
const char line595[] PROGMEM = "s_findServer_intervalTimer = setInterval(RequestFindServer, FIND_SERVER_TIMEOUT_MS)";
const char line596[] PROGMEM = "}";
const char line597[] PROGMEM = "";
const char line598[] PROGMEM = "function RequestFindServer()";
const char line599[] PROGMEM = "{";
const char line600[] PROGMEM = "SendDataToServer(\"&\" + XML_RREQUEST.GetInfo);";
const char line601[] PROGMEM = "}";
const char line602[] PROGMEM = "";
const char line603[] PROGMEM = "function Reset_RequestCurrentDataFromServer_IntervallTimer()";
const char line604[] PROGMEM = "{";
const char line605[] PROGMEM = "clearInterval(s_requestDataFromServer_intervalTimer);";
const char line606[] PROGMEM = "s_requestDataFromServer_intervalTimer = setInterval(RequestCurrentDataFromServer, REQUEST_CURRENT_DATA_FROM_SERVER_TIMEOUT_MS);";
const char line607[] PROGMEM = "}";
const char line608[] PROGMEM = "";
const char line609[] PROGMEM = "function ReleaseLock()";
const char line610[] PROGMEM = "{";
const char line611[] PROGMEM = "s_lock_send_data = false;";
const char line612[] PROGMEM = "s_sendToServer_timeoutTimer = null;";
const char line613[] PROGMEM = "";
const char line614[] PROGMEM = "if (s_is_send_data_pending == true)";
const char line615[] PROGMEM = "{";
const char line616[] PROGMEM = "SendDataToServer(s_pending_xml_request);";
const char line617[] PROGMEM = "s_is_send_data_pending = false;";
const char line618[] PROGMEM = "s_pending_xml_request = \"\";";
const char line619[] PROGMEM = "}";
const char line620[] PROGMEM = "}";
const char line621[] PROGMEM = "";
const char line622[] PROGMEM = "function LightSceneButtonPushed(scene, bt)";
const char line623[] PROGMEM = "{";
const char line624[] PROGMEM = "LightScene_ShowAsActive(scene)";
const char line625[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.SetLightScene + \"=\" + scene);";
const char line626[] PROGMEM = "}";
const char line627[] PROGMEM = "";
const char line628[] PROGMEM = "function LightScene_SetAllAsInactive()";
const char line629[] PROGMEM = "{";
const char line630[] PROGMEM = "var matches = document.getElementsByClassName('active-class');";
const char line631[] PROGMEM = "for (var cnt = 0; cnt < matches.length; cnt++)";
const char line632[] PROGMEM = "{";
const char line633[] PROGMEM = "matches[cnt].classList.remove('active-class');";
const char line634[] PROGMEM = "}";
const char line635[] PROGMEM = "}";
const char line636[] PROGMEM = "";
const char line637[] PROGMEM = "function LightScene_ShowAsActive(scene)";
const char line638[] PROGMEM = "{";
const char line639[] PROGMEM = "LightScene_SetAllAsInactive();";
const char line640[] PROGMEM = "";
const char line641[] PROGMEM = "if (scene < LIGHT_SCENE.NOF)";
const char line642[] PROGMEM = "{";
const char line643[] PROGMEM = "document.getElementById(\"LightScene\" + scene).classList.add(\"active-class\");";
const char line644[] PROGMEM = "}";
const char line645[] PROGMEM = "}";
const char line646[] PROGMEM = "";
const char line647[] PROGMEM = "function BrighntessSliderChanged()";
const char line648[] PROGMEM = "{";
const char line649[] PROGMEM = "var slider = document.getElementById(\"brightness_slider\");";
const char line650[] PROGMEM = "var output = document.getElementById(\"brightness_value\");";
const char line651[] PROGMEM = "output.innerHTML = slider.value;";
const char line652[] PROGMEM = "";
const char line653[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.SetBrightness + \"=\" + slider.value);";
const char line654[] PROGMEM = "}";
const char line655[] PROGMEM = "";
const char line656[] PROGMEM = "function ColorRGBSliderChanged()";
const char line657[] PROGMEM = "{";
const char line658[] PROGMEM = "var slider = document.getElementById(\"color_rgb_slider\");";
const char line659[] PROGMEM = "var output = document.getElementById(\"color_rgb_value\");";
const char line660[] PROGMEM = "";
const char line661[] PROGMEM = "var color = 0;";
const char line662[] PROGMEM = "if (slider.value > 1279)";
const char line663[] PROGMEM = "{";
const char line664[] PROGMEM = "color = 0xFF00FF - (slider.value - 1280);";
const char line665[] PROGMEM = "}";
const char line666[] PROGMEM = "else if (slider.value > 1023)";
const char line667[] PROGMEM = "{";
const char line668[] PROGMEM = "color = 0x0000FF + ((slider.value - 1024) << 16);";
const char line669[] PROGMEM = "}";
const char line670[] PROGMEM = "else if (slider.value > 767)";
const char line671[] PROGMEM = "{";
const char line672[] PROGMEM = "color = 0x00FFFF - ((slider.value - 768) << 8);";
const char line673[] PROGMEM = "}";
const char line674[] PROGMEM = "else if (slider.value > 511)";
const char line675[] PROGMEM = "{";
const char line676[] PROGMEM = "color = 0x00FF00 + (slider.value - 512);";
const char line677[] PROGMEM = "}";
const char line678[] PROGMEM = "else if (slider.value > 255)";
const char line679[] PROGMEM = "{";
const char line680[] PROGMEM = "color = 0xFFFF00 - ((slider.value - 256) << 16);";
const char line681[] PROGMEM = "}";
const char line682[] PROGMEM = "else";
const char line683[] PROGMEM = "{";
const char line684[] PROGMEM = "color = 0xFF0000 + (slider.value << 8);";
const char line685[] PROGMEM = "}";
const char line686[] PROGMEM = "";
const char line687[] PROGMEM = "var colorStr = ('000000' + color.toString(16)).slice(-6);";
const char line688[] PROGMEM = "output.innerHTML = '0x' + colorStr;";
const char line689[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line690[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.SetColor + \"=\" + color);";
const char line691[] PROGMEM = "";
const char line692[] PROGMEM = "";
const char line693[] PROGMEM = "var red = (color >> 16) & 0xFF;";
const char line694[] PROGMEM = "var green = (color >> 8) & 0xFF;";
const char line695[] PROGMEM = "var blue = color & 0xFF;";
const char line696[] PROGMEM = "document.getElementById(\"color_red_value\").innerHTML = red;";
const char line697[] PROGMEM = "document.getElementById(\"color_green_value\").innerHTML = green;";
const char line698[] PROGMEM = "document.getElementById(\"color_blue_value\").innerHTML = blue;";
const char line699[] PROGMEM = "document.getElementById(\"color_red_slider\").value = red;";
const char line700[] PROGMEM = "document.getElementById(\"color_green_slider\").value = green;";
const char line701[] PROGMEM = "document.getElementById(\"color_blue_slider\").value = blue;";
const char line702[] PROGMEM = "}";
const char line703[] PROGMEM = "";
const char line704[] PROGMEM = "function ColorRGBSingleSliderChanged()";
const char line705[] PROGMEM = "{";
const char line706[] PROGMEM = "var red_slider = document.getElementById(\"color_red_slider\");";
const char line707[] PROGMEM = "var green_slider = document.getElementById(\"color_green_slider\");";
const char line708[] PROGMEM = "var blue_slider = document.getElementById(\"color_blue_slider\");";
const char line709[] PROGMEM = "";
const char line710[] PROGMEM = "document.getElementById(\"color_red_value\").innerHTML = red_slider.value;";
const char line711[] PROGMEM = "document.getElementById(\"color_green_value\").innerHTML = green_slider.value;";
const char line712[] PROGMEM = "document.getElementById(\"color_blue_value\").innerHTML = blue_slider.value;";
const char line713[] PROGMEM = "";
const char line714[] PROGMEM = "var color = 0;";
const char line715[] PROGMEM = "color = (red_slider.value << 16);";
const char line716[] PROGMEM = "color |= (green_slider.value << 8);";
const char line717[] PROGMEM = "color |= blue_slider.value";
const char line718[] PROGMEM = "";
const char line719[] PROGMEM = "var colorStr = ('000000' + color.toString(16)).slice(-6);";
const char line720[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line721[] PROGMEM = "document.getElementById(\"color_rgb_value\").innerHTML = colorStr;";
const char line722[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.SetColor + \"=\" + color);";
const char line723[] PROGMEM = "}";
const char line724[] PROGMEM = "";
const char line725[] PROGMEM = "function ColorWhiteSliderChanged()";
const char line726[] PROGMEM = "{";
const char line727[] PROGMEM = "var slider = document.getElementById(\"color_white_slider\");";
const char line728[] PROGMEM = "var output = document.getElementById(\"color_white_value\");";
const char line729[] PROGMEM = "";
const char line730[] PROGMEM = "var color = slider.value;";
const char line731[] PROGMEM = "output.innerHTML = color;";
const char line732[] PROGMEM = "colorStr = ('000000' + ((color << 16) | (color << 8) | color).toString(16)).slice(-6);";
const char line733[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line734[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.SetColor + \"=\" + (slider.value << 24));";
const char line735[] PROGMEM = "}";
const char line736[] PROGMEM = "";
const char line737[] PROGMEM = "// 2 thumb slider";
const char line738[] PROGMEM = "\"use strict\";";
const char line739[] PROGMEM = "addEventListener('input', e => {";
const char line740[] PROGMEM = "if (e.target.classList.contains(\"twoThumbSlider\"))";
const char line741[] PROGMEM = "{";
const char line742[] PROGMEM = "let _t = e.target;";
const char line743[] PROGMEM = "";
const char line744[] PROGMEM = "_t.parentNode.style.setProperty(`--${_t.id}`, +_t.value);";
const char line745[] PROGMEM = "";
const char line746[] PROGMEM = "SliderTwoThumb_Update();";
const char line747[] PROGMEM = "}";
const char line748[] PROGMEM = "}, false);";
const char line749[] PROGMEM = "";
const char line750[] PROGMEM = "function SliderTwoThumb_Update()";
const char line751[] PROGMEM = "{";
const char line752[] PROGMEM = "var xs = parseInt(getComputedStyle(document.getElementById(\"slider_columen\")).getPropertyValue('--a'), 10);";
const char line753[] PROGMEM = "var xe = parseInt(getComputedStyle(document.getElementById(\"slider_columen\")).getPropertyValue('--b'), 10);";
const char line754[] PROGMEM = "var ys = parseInt(getComputedStyle(document.getElementById(\"slider_row\")).getPropertyValue('--a'), 10);";
const char line755[] PROGMEM = "var ye = parseInt(getComputedStyle(document.getElementById(\"slider_row\")).getPropertyValue('--b'), 10);";
const char line756[] PROGMEM = "";
const char line757[] PROGMEM = "if (xs > xe)";
const char line758[] PROGMEM = "{";
const char line759[] PROGMEM = "var tmp = xs;";
const char line760[] PROGMEM = "xs = xe;";
const char line761[] PROGMEM = "xe = tmp;";
const char line762[] PROGMEM = "}";
const char line763[] PROGMEM = "if (ys > ye)";
const char line764[] PROGMEM = "{";
const char line765[] PROGMEM = "var tmp = ys;";
const char line766[] PROGMEM = "ys = ye;";
const char line767[] PROGMEM = "ye = tmp;";
const char line768[] PROGMEM = "}";
const char line769[] PROGMEM = "";
const char line770[] PROGMEM = "SendDataToServerWhenConnected(\"&\" + XML_RREQUEST.SetArea + \"=X\" + xs + \"-\" + xe + \"Y\" + ys + \"-\" + ye);";
const char line771[] PROGMEM = "xs += USER_SETTING_OFFSET;";
const char line772[] PROGMEM = "xe += USER_SETTING_OFFSET;";
const char line773[] PROGMEM = "ys += USER_SETTING_OFFSET;";
const char line774[] PROGMEM = "ye += USER_SETTING_OFFSET;";
const char line775[] PROGMEM = "document.getElementById(\"led_column\").innerHTML = (xs + \" - \" + xe);";
const char line776[] PROGMEM = "document.getElementById(\"led_row\").innerHTML = (ys + \" - \" + ye);";
const char line777[] PROGMEM = "}";
const char line778[] PROGMEM = "";
const char line779[] PROGMEM = "";
const char line780[] PROGMEM = "//--- onload event handler ----------------------------------------";
const char line781[] PROGMEM = "window.addEventListener('load', (event) =>";
const char line782[] PROGMEM = "{";
const char line783[] PROGMEM = "var button = '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.PowerOff + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.PowerOff, this)\">Off</div>'";
const char line784[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.OfficeTable + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.OfficeTable, this)\">B&uuml;rotisch</div>'";
const char line785[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Moba + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Moba, this)\">MoBa</div>'";
const char line786[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.LightOn + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.LightOn, this)\">All On</div>'";
const char line787[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Rainbow + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Rainbow, this)\">Rainbow</div>'";
const char line788[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Disco + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Disco, this)\">Disco</div>'";
const char line789[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.UserSetting + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.UserSetting, this)\">User Set</div>'";
const char line790[] PROGMEM = "+ '<br>'";
const char line791[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Sunrise + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Sunrise, this)\">Sunrise</div>'";
const char line792[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Day + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Day, this)\">Day</div>'";
const char line793[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Sunset + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Sunset, this)\">Sunset</div>'";
const char line794[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Night + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Night, this)\">Night</div>'";
const char line795[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Cloud + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Cloud, this)\">Clouds</div>'";
const char line796[] PROGMEM = "+ '<div class=\"button\" id=\"LightScene' + LIGHT_SCENE.Lightning + '\" onclick=\"LightSceneButtonPushed(LIGHT_SCENE.Lightning, this)\">Lightning</div>';";
const char line797[] PROGMEM = "";
const char line798[] PROGMEM = "document.getElementById(\"LightScene\").innerHTML = button;";
const char line799[] PROGMEM = "document.getElementById(\"footer_version\").innerHTML = (\"v\" + GLOBAL_WebserverVersion_Major + \".\" + GLOBAL_WebserverVersion_Minor);";
const char line800[] PROGMEM = "";
const char line801[] PROGMEM = "FindServer();";
const char line802[] PROGMEM = "});";
const char line803[] PROGMEM = "";
const char line804[] PROGMEM = "</script>";
const char line805[] PROGMEM = "</head>";
const char line806[] PROGMEM = "";
const char line807[] PROGMEM = "<body>";
const char line808[] PROGMEM = "<div class=\"box\">";
const char line809[] PROGMEM = "<div class=\"box_header\">Licht Szene</div>";
const char line810[] PROGMEM = "<div id=\"LightScene\" class=\"box_content\"></div>";
const char line811[] PROGMEM = "</div>";
const char line812[] PROGMEM = "<br>";
const char line813[] PROGMEM = "";
const char line814[] PROGMEM = "<div class=\"box\">";
const char line815[] PROGMEM = "<div class=\"box_header\">Helligkeit / Farbe</div>";
const char line816[] PROGMEM = "<div class=\"box_content\">";
const char line817[] PROGMEM = "<div class=\"slidecontainer\">";
const char line818[] PROGMEM = "<label for=\"brightness_value\">Helligkeit</label>";
const char line819[] PROGMEM = "<label id=\"brightness_value\" class=\"user_value\"></label>";
const char line820[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"brightness_slider\" oninput=\"BrighntessSliderChanged()\">";
const char line821[] PROGMEM = "</div>";
const char line822[] PROGMEM = "<br>";
const char line823[] PROGMEM = "";
const char line824[] PROGMEM = "<div class=\"slidecontainer\">";
const char line825[] PROGMEM = "<label for=\"color_rgb_value\">RGB</label>";
const char line826[] PROGMEM = "<label id=\"color_rgb_value\" class=\"user_value\"></label>";
const char line827[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"1535\" value=\"50\" class=\"slider\" id=\"color_rgb_slider\" oninput=\"ColorRGBSliderChanged()\" style=\"background-image: linear-gradient(90deg, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff, #ff0000);\">";
const char line828[] PROGMEM = "</div>";
const char line829[] PROGMEM = "<div class=\"slidecontainer\">";
const char line830[] PROGMEM = "<label for=\"color_red_value\">Rot</label>";
const char line831[] PROGMEM = "<label id=\"color_red_value\" class=\"user_value\"></label>";
const char line832[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_red_slider\" oninput=\"ColorRGBSingleSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, red)\">";
const char line833[] PROGMEM = "</div>";
const char line834[] PROGMEM = "<div class=\"slidecontainer\">";
const char line835[] PROGMEM = "<label for=\"color_green_value\">Gr&uuml;n</label>";
const char line836[] PROGMEM = "<label id=\"color_green_value\" class=\"user_value\"></label>";
const char line837[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_green_slider\" oninput=\"ColorRGBSingleSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, rgb(0, 255, 0))\">";
const char line838[] PROGMEM = "</div>";
const char line839[] PROGMEM = "<div class=\"slidecontainer\">";
const char line840[] PROGMEM = "<label for=\"color_blue_value\">Blau</label>";
const char line841[] PROGMEM = "<label id=\"color_blue_value\" class=\"user_value\"></label>";
const char line842[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_blue_slider\" oninput=\"ColorRGBSingleSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, blue)\">";
const char line843[] PROGMEM = "</div>";
const char line844[] PROGMEM = "<div class=\"slidecontainer\">";
const char line845[] PROGMEM = "<label for=\"color_white_value\">Weiss</label>";
const char line846[] PROGMEM = "<label id=\"color_white_value\" class=\"user_value\"></label>";
const char line847[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_white_slider\" oninput=\"ColorWhiteSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, white)\">";
const char line848[] PROGMEM = "</div>";
const char line849[] PROGMEM = "</div>";
const char line850[] PROGMEM = "</div>";
const char line851[] PROGMEM = "<br>";
const char line852[] PROGMEM = "";
const char line853[] PROGMEM = "<div class=\"box\">";
const char line854[] PROGMEM = "<div class=\"box_header\">User Set: Beleuchtungsbereich</div>";
const char line855[] PROGMEM = "<div class=\"box_content\">";
const char line856[] PROGMEM = "<table style=\"width: 100%;\">";
const char line857[] PROGMEM = "<tr>";
const char line858[] PROGMEM = "<td>";
const char line859[] PROGMEM = "<label for=\"led_row\">Reihen</label>";
const char line860[] PROGMEM = "<label type=\"text\" id=\"led_row\" class=\"user_value\"> loading...</label>";
const char line861[] PROGMEM = "</td>";
const char line862[] PROGMEM = "<td>";
const char line863[] PROGMEM = "<label for=\"led_column\">L&auml;nge</label>";
const char line864[] PROGMEM = "<label type=\"text\" id=\"led_column\" class=\"user_value\"> loading...</label>";
const char line865[] PROGMEM = "</td>";
const char line866[] PROGMEM = "</tr>";
const char line867[] PROGMEM = "<tr>";
const char line868[] PROGMEM = "<td id=\"led_slider_row\">";
const char line869[] PROGMEM = "</td>";
const char line870[] PROGMEM = "<td id=led_slider_column>";
const char line871[] PROGMEM = "</td>";
const char line872[] PROGMEM = "</tr>";
const char line873[] PROGMEM = "</table>";
const char line874[] PROGMEM = "</div>";
const char line875[] PROGMEM = "</div>";
const char line876[] PROGMEM = "</body>";
const char line877[] PROGMEM = "</html>";
const char line878[] PROGMEM = "<html>";
const char line879[] PROGMEM = "<footer>";
const char line880[] PROGMEM = "<div>";
const char line881[] PROGMEM = "<br>";
const char line882[] PROGMEM = "<hr>";
const char line883[] PROGMEM = "<div id=\"footer_version\" style=\"float:left\">vX.Y</div>";
const char line884[] PROGMEM = "&nbsp;&nbsp;|&nbsp;&nbsp;22. May 2023 &nbsp; &copy; MarkusNTrains";
const char line885[] PROGMEM = "<a href='mailto:markusntrains@gmx.ch'>E-Mail</a>";
const char line886[] PROGMEM = "</div>";
const char line887[] PROGMEM = "</footer>";
const char line888[] PROGMEM = "</html>";

const char* const website_a[] PROGMEM = {line1, line2, line3, line4, line5, line6, line7, line8, line9, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, line21, line22, line23, line24, line25, line26, line27, line28, line29, line30, line31, line32, line33, line34, line35, line36, line37, line38, line39, line40, line41, line42, line43, line44, line45, line46, line47, line48, line49, line50, line51, line52, line53, line54, line55, line56, line57, line58, line59, line60, line61, line62, line63, line64, line65, line66, line67, line68, line69, line70, line71, line72, line73, line74, line75, line76, line77, line78, line79, line80, line81, line82, line83, line84, line85, line86, line87, line88, line89, line90, line91, line92, line93, line94, line95, line96, line97, line98, line99, line100, line101, line102, line103, line104, line105, line106, line107, line108, line109, line110, line111, line112, line113, line114, line115, line116, line117, line118, line119, line120, line121, line122, line123, line124, line125, line126, line127, line128, line129, line130, line131, line132, line133, line134, line135, line136, line137, line138, line139, line140, line141, line142, line143, line144, line145, line146, line147, line148, line149, line150, line151, line152, line153, line154, line155, line156, line157, line158, line159, line160, line161, line162, line163, line164, line165, line166, line167, line168, line169, line170, line171, line172, line173, line174, line175, line176, line177, line178, line179, line180, line181, line182, line183, line184, line185, line186, line187, line188, line189, line190, line191, line192, line193, line194, line195, line196, line197, line198, line199, line200, line201, line202, line203, line204, line205, line206, line207, line208, line209, line210, line211, line212, line213, line214, line215, line216, line217, line218, line219, line220, line221, line222, line223, line224, line225, line226, line227, line228, line229, line230, line231, line232, line233, line234, line235, line236, line237, line238, line239, line240, line241, line242, line243, line244, line245, line246, line247, line248, line249, line250, line251, line252, line253, line254, line255, line256, line257, line258, line259, line260, line261, line262, line263, line264, line265, line266, line267, line268, line269, line270, line271, line272, line273, line274, line275, line276, line277, line278, line279, line280, line281, line282, line283, line284, line285, line286, line287, line288, line289, line290, line291, line292, line293, line294, line295, line296, line297, line298, line299, line300, line301, line302, line303, line304, line305, line306, line307, line308, line309, line310, line311, line312, line313, line314, line315, line316, line317, line318, line319, line320, line321, line322, line323, line324, line325, line326, line327, line328, line329, line330, line331, line332, line333, line334, line335, line336, line337, line338, line339, line340, line341, line342, line343, line344, line345, line346, line347, line348, line349, line350, line351, line352, line353, line354, line355, line356, line357, line358, line359, line360, line361, line362, line363, line364, line365, line366, line367, line368, line369, line370, line371, line372, line373, line374, line375, line376, line377, line378, line379, line380, line381, line382, line383, line384, line385, line386, line387, line388, line389, line390, line391, line392, line393, line394, line395, line396, line397, line398, line399, line400, line401, line402, line403, line404, line405, line406, line407, line408, line409, line410, line411, line412, line413, line414, line415, line416, line417, line418, line419, line420, line421, line422, line423, line424, line425, line426, line427, line428, line429, line430, line431, line432, line433, line434, line435, line436, line437, line438, line439, line440, line441, line442, line443, line444, line445, line446, line447, line448, line449, line450, line451, line452, line453, line454, line455, line456, line457, line458, line459, line460, line461, line462, line463, line464, line465, line466, line467, line468, line469, line470, line471, line472, line473, line474, line475, line476, line477, line478, line479, line480, line481, line482, line483, line484, line485, line486, line487, line488, line489, line490, line491, line492, line493, line494, line495, line496, line497, line498, line499, line500, line501, line502, line503, line504, line505, line506, line507, line508, line509, line510, line511, line512, line513, line514, line515, line516, line517, line518, line519, line520, line521, line522, line523, line524, line525, line526, line527, line528, line529, line530, line531, line532, line533, line534, line535, line536, line537, line538, line539, line540, line541, line542, line543, line544, line545, line546, line547, line548, line549, line550, line551, line552, line553, line554, line555, line556, line557, line558, line559, line560, line561, line562, line563, line564, line565, line566, line567, line568, line569, line570, line571, line572, line573, line574, line575, line576, line577, line578, line579, line580, line581, line582, line583, line584, line585, line586, line587, line588, line589, line590, line591, line592, line593, line594, line595, line596, line597, line598, line599, line600, line601, line602, line603, line604, line605, line606, line607, line608, line609, line610, line611, line612, line613, line614, line615, line616, line617, line618, line619, line620, line621, line622, line623, line624, line625, line626, line627, line628, line629, line630, line631, line632, line633, line634, line635, line636, line637, line638, line639, line640, line641, line642, line643, line644, line645, line646, line647, line648, line649, line650, line651, line652, line653, line654, line655, line656, line657, line658, line659, line660, line661, line662, line663, line664, line665, line666, line667, line668, line669, line670, line671, line672, line673, line674, line675, line676, line677, line678, line679, line680, line681, line682, line683, line684, line685, line686, line687, line688, line689, line690, line691, line692, line693, line694, line695, line696, line697, line698, line699, line700, line701, line702, line703, line704, line705, line706, line707, line708, line709, line710, line711, line712, line713, line714, line715, line716, line717, line718, line719, line720, line721, line722, line723, line724, line725, line726, line727, line728, line729, line730, line731, line732, line733, line734, line735, line736, line737, line738, line739, line740, line741, line742, line743, line744, line745, line746, line747, line748, line749, line750, line751, line752, line753, line754, line755, line756, line757, line758, line759, line760, line761, line762, line763, line764, line765, line766, line767, line768, line769, line770, line771, line772, line773, line774, line775, line776, line777, line778, line779, line780, line781, line782, line783, line784, line785, line786, line787, line788, line789, line790, line791, line792, line793, line794, line795, line796, line797, line798, line799, line800, line801, line802, line803, line804, line805, line806, line807, line808, line809, line810, line811, line812, line813, line814, line815, line816, line817, line818, line819, line820, line821, line822, line823, line824, line825, line826, line827, line828, line829, line830, line831, line832, line833, line834, line835, line836, line837, line838, line839, line840, line841, line842, line843, line844, line845, line846, line847, line848, line849, line850, line851, line852, line853, line854, line855, line856, line857, line858, line859, line860, line861, line862, line863, line864, line865, line866, line867, line868, line869, line870, line871, line872, line873, line874, line875, line876, line877, line878, line879, line880, line881, line882, line883, line884, line885, line886, line887, line888};


//-----------------------------------------------------------------------------
// define
#define WEBSITE_NOF_LINES 888


//-----------------------------------------------------------------------------
// static module variable



//*****************************************************************************
// description:
//   Website_SendToClient
//*****************************************************************************
void Website_SendToClient(EthernetClient* client)
{
	uint32_t line = 0;
    char line_str[253];

	for (line = 0; line < WEBSITE_NOF_LINES; line++)
	{
        strcpy_P(line_str, (char*)pgm_read_word(&(website_a[line])));
		client->println(line_str);
	}
}
