/*******************************************************************************
Project   RoomLight

  This is an OpenSource Project.
  You can use, share or improve this project. If you improve this source code
  please share with the comunity or at least with the author of the original
  source code

  Created 29. October 2021 by MarkusNTrains
================================================================================
$HeadURL:  $
$Id:  $
*******************************************************************************/


//-----------------------------------------------------------------------------
// includes
#include "Website.h"


//-----------------------------------------------------------------------------
// PROGMEM -> store data in flash
const char line1[] PROGMEM = "<!doctype html>";
const char line2[] PROGMEM = "<html lang=\"en\">";
const char line3[] PROGMEM = "<head>";
const char line4[] PROGMEM = "<meta charset=\"utf-8\">";
const char line5[] PROGMEM = "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
const char line6[] PROGMEM = "<title>MoBa Room Light</title>";
const char line7[] PROGMEM = "<!--<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">";
const char line8[] PROGMEM = "<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>";
const char line9[] PROGMEM = "<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>-->";
const char line10[] PROGMEM = "<!--\t<script src=\"jquery-1.12.4.js\"></script>";
const char line11[] PROGMEM = "<script src=\"jquery-ui.js\"></script> -->";
const char line12[] PROGMEM = "<script type=\"text/javascript\" charset=\"utf-8\">";
const char line13[] PROGMEM = "const LightScene =";
const char line14[] PROGMEM = "{";
const char line15[] PROGMEM = "OFFICE_TABLE_WW: 0,";
const char line16[] PROGMEM = "LIGHT_ON_WW: 1,";
const char line17[] PROGMEM = "DISCO: 2,";
const char line18[] PROGMEM = "SUNSET: 3,";
const char line19[] PROGMEM = "SUNRISE: 4,";
const char line20[] PROGMEM = "POWER_OFF: 5,";
const char line21[] PROGMEM = "IDLE: 6";
const char line22[] PROGMEM = "};";
const char line23[] PROGMEM = "";
const char line24[] PROGMEM = "";
const char line25[] PROGMEM = "var xml_request = \"\";";
const char line26[] PROGMEM = "var s_lock_send_data = false;";
const char line27[] PROGMEM = "var s_is_send_data_pending = false;";
const char line28[] PROGMEM = "";
const char line29[] PROGMEM = "function ReleaseLock()";
const char line30[] PROGMEM = "{";
const char line31[] PROGMEM = "s_lock_send_data = false;";
const char line32[] PROGMEM = "if (s_is_send_data_pending == true)";
const char line33[] PROGMEM = "{";
const char line34[] PROGMEM = "SendDataToArduino();";
const char line35[] PROGMEM = "}";
const char line36[] PROGMEM = "}";
const char line37[] PROGMEM = "";
const char line38[] PROGMEM = "function SendDataToArduino()";
const char line39[] PROGMEM = "{";
const char line40[] PROGMEM = "if (s_lock_send_data == false)";
const char line41[] PROGMEM = "{";
const char line42[] PROGMEM = "nocache = \"&nocache=\" + Math.random() * 1000000;";
const char line43[] PROGMEM = "var request = new XMLHttpRequest();";
const char line44[] PROGMEM = "request.onreadystatechange = function()";
const char line45[] PROGMEM = "{";
const char line46[] PROGMEM = "if (this.readyState == 4)";
const char line47[] PROGMEM = "{";
const char line48[] PROGMEM = "if (this.status == 200)";
const char line49[] PROGMEM = "{";
const char line50[] PROGMEM = "if (this.responseXML != null)";
const char line51[] PROGMEM = "{";
const char line52[] PROGMEM = "// XML file received - contains LED states";
const char line53[] PROGMEM = "var re;";
const char line54[] PROGMEM = "var num_LEDs;";
const char line55[] PROGMEM = "var i;";
const char line56[] PROGMEM = "var ledstr = \"\";";
const char line57[] PROGMEM = "";
const char line58[] PROGMEM = "/*re = this.responseXML.getElementsByTagName('LED');";
const char line59[] PROGMEM = "num_LEDs = re.length;";
const char line60[] PROGMEM = "";
const char line61[] PROGMEM = "for (i = 0; i < num_LEDs; i++)";
const char line62[] PROGMEM = "{";
const char line63[] PROGMEM = "ledstr = \"LED\" + (i + 1);";
const char line64[] PROGMEM = "if (re[i].childNodes[0].nodeValue === \"checked\")";
const char line65[] PROGMEM = "{";
const char line66[] PROGMEM = "document.getElementsByName(ledstr)[0].checked = true;";
const char line67[] PROGMEM = "}";
const char line68[] PROGMEM = "else";
const char line69[] PROGMEM = "{";
const char line70[] PROGMEM = "document.getElementsByName(ledstr)[0].checked = false;";
const char line71[] PROGMEM = "}";
const char line72[] PROGMEM = "}*/";
const char line73[] PROGMEM = "";
const char line74[] PROGMEM = "";
const char line75[] PROGMEM = "";
const char line76[] PROGMEM = "//re = this.responseXML.getElementsByTagName('scene');";
const char line77[] PROGMEM = "";
const char line78[] PROGMEM = "";
const char line79[] PROGMEM = "re = this.responseXML.getElementsByTagName('brightness');";
const char line80[] PROGMEM = "document.getElementById(\"brightness_slider\").value = re[0].childNodes[0].nodeValue;";
const char line81[] PROGMEM = "document.getElementById(\"brightness_value\").innerHTML = re[0].childNodes[0].nodeValue;";
const char line82[] PROGMEM = "";
const char line83[] PROGMEM = "}";
const char line84[] PROGMEM = "}";
const char line85[] PROGMEM = "}";
const char line86[] PROGMEM = "}";
const char line87[] PROGMEM = "// send HTTP GET request with LEDs to switch on/off if any";
const char line88[] PROGMEM = "request.open(\"GET\", \"ajax_inputs\" + xml_request + nocache, true);";
const char line89[] PROGMEM = "request.send(null);";
const char line90[] PROGMEM = "xml_request = \"\";";
const char line91[] PROGMEM = "s_is_send_data_pending = false;";
const char line92[] PROGMEM = "";
const char line93[] PROGMEM = "// lock Send to Arduino";
const char line94[] PROGMEM = "setTimeout('ReleaseLock()', 200);";
const char line95[] PROGMEM = "s_lock_send_data = true;";
const char line96[] PROGMEM = "}";
const char line97[] PROGMEM = "else";
const char line98[] PROGMEM = "{";
const char line99[] PROGMEM = "s_is_send_data_pending = true;";
const char line100[] PROGMEM = "}";
const char line101[] PROGMEM = "}";
const char line102[] PROGMEM = "";
const char line103[] PROGMEM = "// service LEDs when checkbox checked/unchecked";
const char line104[] PROGMEM = "/*function GetCheck(led_num_str, cb)";
const char line105[] PROGMEM = "{";
const char line106[] PROGMEM = "if (cb.checked) {";
const char line107[] PROGMEM = "strLED += (\"&\" + led_num_str + \"=1\");";
const char line108[] PROGMEM = "}";
const char line109[] PROGMEM = "else {";
const char line110[] PROGMEM = "strLED += (\"&\" + led_num_str + \"=0\");";
const char line111[] PROGMEM = "}";
const char line112[] PROGMEM = "}*/";
const char line113[] PROGMEM = "";
const char line114[] PROGMEM = "function LightSceneButtonPushed(scene, bt)";
const char line115[] PROGMEM = "{";
const char line116[] PROGMEM = "var matches = document.getElementsByClassName('active-class');";
const char line117[] PROGMEM = "";
const char line118[] PROGMEM = "for (var cnt = 0; cnt < matches.length; cnt++)";
const char line119[] PROGMEM = "{";
const char line120[] PROGMEM = "matches[cnt].classList.remove('active-class');";
const char line121[] PROGMEM = "}";
const char line122[] PROGMEM = "";
const char line123[] PROGMEM = "bt.classList.add(\"active-class\");";
const char line124[] PROGMEM = "";
const char line125[] PROGMEM = "xml_request = \"&LightScene=\" + scene;";
const char line126[] PROGMEM = "SendDataToArduino();";
const char line127[] PROGMEM = "}";
const char line128[] PROGMEM = "";
const char line129[] PROGMEM = "function BrighntessSliderChanged()";
const char line130[] PROGMEM = "{";
const char line131[] PROGMEM = "var slider = document.getElementById(\"brightness_slider\");";
const char line132[] PROGMEM = "var output = document.getElementById(\"brightness_value\");";
const char line133[] PROGMEM = "output.innerHTML = slider.value;";
const char line134[] PROGMEM = "";
const char line135[] PROGMEM = "/*slider.oninput = function()";
const char line136[] PROGMEM = "{";
const char line137[] PROGMEM = "output.innerHTML = slider.value;";
const char line138[] PROGMEM = "}*/";
const char line139[] PROGMEM = "";
const char line140[] PROGMEM = "xml_request = \"&SetBrightness=\" + slider.value;";
const char line141[] PROGMEM = "SendDataToArduino();";
const char line142[] PROGMEM = "}";
const char line143[] PROGMEM = "";
const char line144[] PROGMEM = "// 2 thumb slider";
const char line145[] PROGMEM = "\"use strict\";";
const char line146[] PROGMEM = "addEventListener('input', e => {";
const char line147[] PROGMEM = "if (e.target.classList.contains(\"twoThumbSlider\"))";
const char line148[] PROGMEM = "{";
const char line149[] PROGMEM = "let _t = e.target;";
const char line150[] PROGMEM = "";
const char line151[] PROGMEM = "_t.parentNode.style.setProperty(`--${_t.id}`, +_t.value);";
const char line152[] PROGMEM = "";
const char line153[] PROGMEM = "SliderTwoThumb_Update();";
const char line154[] PROGMEM = "}";
const char line155[] PROGMEM = "}, false);";
const char line156[] PROGMEM = "";
const char line157[] PROGMEM = "function SliderTwoThumb_Update()";
const char line158[] PROGMEM = "{";
const char line159[] PROGMEM = "var xs = parseInt(getComputedStyle(document.getElementById(\"slider_columen\")).getPropertyValue('--a'), 10);";
const char line160[] PROGMEM = "var xe = parseInt(getComputedStyle(document.getElementById(\"slider_columen\")).getPropertyValue('--b'), 10);";
const char line161[] PROGMEM = "var ys = parseInt(getComputedStyle(document.getElementById(\"slider_row\")).getPropertyValue('--a'), 10);";
const char line162[] PROGMEM = "var ye = parseInt(getComputedStyle(document.getElementById(\"slider_row\")).getPropertyValue('--b'), 10);";
const char line163[] PROGMEM = "";
const char line164[] PROGMEM = "if (xs > xe)";
const char line165[] PROGMEM = "{";
const char line166[] PROGMEM = "var tmp = xs;";
const char line167[] PROGMEM = "xs = xe;";
const char line168[] PROGMEM = "xe = tmp;";
const char line169[] PROGMEM = "}";
const char line170[] PROGMEM = "if (ys > ye)";
const char line171[] PROGMEM = "{";
const char line172[] PROGMEM = "var tmp = ys;";
const char line173[] PROGMEM = "ys = ye;";
const char line174[] PROGMEM = "ye = tmp;";
const char line175[] PROGMEM = "}";
const char line176[] PROGMEM = "";
const char line177[] PROGMEM = "document.getElementById(\"led_column\").innerHTML = (xs + \" - \" + xe);";
const char line178[] PROGMEM = "document.getElementById(\"led_row\").innerHTML = (ys + \" - \" + ye);";
const char line179[] PROGMEM = "xml_request = \"&SetArea=X\" + xs + \"-\" + xe + \"Y\" + ys + \"-\" + ye;";
const char line180[] PROGMEM = "SendDataToArduino();";
const char line181[] PROGMEM = "}";
const char line182[] PROGMEM = "";
const char line183[] PROGMEM = "// on load";
const char line184[] PROGMEM = "window.onload = function() {";
const char line185[] PROGMEM = "SliderTwoThumb_Update();";
const char line186[] PROGMEM = "};";
const char line187[] PROGMEM = "";
const char line188[] PROGMEM = "</script>";
const char line189[] PROGMEM = "";
const char line190[] PROGMEM = "";
const char line191[] PROGMEM = "<style type=\"text/css\">";
const char line192[] PROGMEM = ".out_box {";
const char line193[] PROGMEM = "float: left;";
const char line194[] PROGMEM = "margin: 0 20px 20px 0;";
const char line195[] PROGMEM = "border: 1px solid blue;";
const char line196[] PROGMEM = "padding: 0 5px 0 5px;";
const char line197[] PROGMEM = "min-width: 280px;";
const char line198[] PROGMEM = "}";
const char line199[] PROGMEM = "input {";
const char line200[] PROGMEM = "margin: 10px;";
const char line201[] PROGMEM = "}";
const char line202[] PROGMEM = "input {";
const char line203[] PROGMEM = "vertical-align: -3px;";
const char line204[] PROGMEM = "}";
const char line205[] PROGMEM = "h1 {";
const char line206[] PROGMEM = "font-size: 150%;";
const char line207[] PROGMEM = "color: black;";
const char line208[] PROGMEM = "margin: 0 0 10px 0;";
const char line209[] PROGMEM = "width: calc(100% - 32px);";
const char line210[] PROGMEM = "border-radius: 4px;";
const char line211[] PROGMEM = "padding: 8px 16px 8px 16px;";
const char line212[] PROGMEM = "border: 2px solid #000000;";
const char line213[] PROGMEM = "}";
const char line214[] PROGMEM = "h2 {";
const char line215[] PROGMEM = "font-size: 120%;";
const char line216[] PROGMEM = "color: #2f0fb3;";
const char line217[] PROGMEM = "margin: 5px 0 5px 0;";
const char line218[] PROGMEM = "width: calc(100% - 32px);";
const char line219[] PROGMEM = "border-radius: 4px;";
const char line220[] PROGMEM = "padding: 8px 16px 8px 16px;";
const char line221[] PROGMEM = "border: 2px solid #2f0fb3;";
const char line222[] PROGMEM = "}";
const char line223[] PROGMEM = "p, form, button {";
const char line224[] PROGMEM = "font-size: 80%;";
const char line225[] PROGMEM = "color: #252525;";
const char line226[] PROGMEM = "}";
const char line227[] PROGMEM = ".small_text {";
const char line228[] PROGMEM = "font-size: 70%;";
const char line229[] PROGMEM = "color: #737373;";
const char line230[] PROGMEM = "}";
const char line231[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line232[] PROGMEM = "/* button */";
const char line233[] PROGMEM = ".button {";
const char line234[] PROGMEM = "background-color: #4CAF50; /* Green */";
const char line235[] PROGMEM = "border: none;";
const char line236[] PROGMEM = "border-radius: 4px;";
const char line237[] PROGMEM = "color: white;";
const char line238[] PROGMEM = "padding: 16px 32px;";
const char line239[] PROGMEM = "text-align: center;";
const char line240[] PROGMEM = "text-decoration: none;";
const char line241[] PROGMEM = "display: inline-block;";
const char line242[] PROGMEM = "font-size: 16px;";
const char line243[] PROGMEM = "margin: 4px 2px;";
const char line244[] PROGMEM = "-webkit-transition-duration: 0.4s; /* Safari */";
const char line245[] PROGMEM = "transition-duration: 0.4s;";
const char line246[] PROGMEM = "cursor: pointer;";
const char line247[] PROGMEM = "}";
const char line248[] PROGMEM = "";
const char line249[] PROGMEM = ".button {";
const char line250[] PROGMEM = "background-color: white;";
const char line251[] PROGMEM = "color: black;";
const char line252[] PROGMEM = "border: 2px solid #4CAF50;";
const char line253[] PROGMEM = "}";
const char line254[] PROGMEM = "";
const char line255[] PROGMEM = ".button:hover {";
const char line256[] PROGMEM = "background-color: #4CAF50;";
const char line257[] PROGMEM = "color: black;";
const char line258[] PROGMEM = "}";
const char line259[] PROGMEM = ".button:active {";
const char line260[] PROGMEM = "background-color: #337536;";
const char line261[] PROGMEM = "color: white;";
const char line262[] PROGMEM = "transform: translateY(2px);";
const char line263[] PROGMEM = "}";
const char line264[] PROGMEM = ".active-class {";
const char line265[] PROGMEM = "background-color: #337536;";
const char line266[] PROGMEM = "color: white;";
const char line267[] PROGMEM = "}";
const char line268[] PROGMEM = "";
const char line269[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line270[] PROGMEM = "/* slider */";
const char line271[] PROGMEM = ".slidecontainer {";
const char line272[] PROGMEM = "width: 100%;";
const char line273[] PROGMEM = "}";
const char line274[] PROGMEM = "";
const char line275[] PROGMEM = ".slider {";
const char line276[] PROGMEM = "-webkit-appearance: none;";
const char line277[] PROGMEM = "-moz-appearance: none;";
const char line278[] PROGMEM = "width: 100%;";
const char line279[] PROGMEM = "height: 15px;";
const char line280[] PROGMEM = "border-radius: 5px;";
const char line281[] PROGMEM = "background: #d3d3d3;";
const char line282[] PROGMEM = "outline: none;";
const char line283[] PROGMEM = "opacity: 0.7;";
const char line284[] PROGMEM = "-webkit-transition: .2s;";
const char line285[] PROGMEM = "transition: opacity .2s;";
const char line286[] PROGMEM = "}";
const char line287[] PROGMEM = "";
const char line288[] PROGMEM = ".slider::-webkit-slider-thumb {";
const char line289[] PROGMEM = "-webkit-appearance: none;";
const char line290[] PROGMEM = "-moz-appearance: none;";
const char line291[] PROGMEM = "appearance: none;";
const char line292[] PROGMEM = "width: 25px;";
const char line293[] PROGMEM = "height: 25px;";
const char line294[] PROGMEM = "border-radius: 50%;";
const char line295[] PROGMEM = "background: #4CAF50;";
const char line296[] PROGMEM = "cursor: pointer;";
const char line297[] PROGMEM = "}";
const char line298[] PROGMEM = "";
const char line299[] PROGMEM = ".slider::-moz-range-thumb {";
const char line300[] PROGMEM = "width: 25px;";
const char line301[] PROGMEM = "height: 25px;";
const char line302[] PROGMEM = "border-radius: 50%;";
const char line303[] PROGMEM = "background: #4CAF50;";
const char line304[] PROGMEM = "cursor: pointer;";
const char line305[] PROGMEM = "}";
const char line306[] PROGMEM = "";
const char line307[] PROGMEM = "";
const char line308[] PROGMEM = "/*---------------------------------------------------------------------*/";
const char line309[] PROGMEM = "/* 2 thumb slider */";
const char line310[] PROGMEM = "#led_slider_row {";
const char line311[] PROGMEM = "width: 100px;";
const char line312[] PROGMEM = "height: 4em;";
const char line313[] PROGMEM = "}";
const char line314[] PROGMEM = "";
const char line315[] PROGMEM = "#led_slider_column {";
const char line316[] PROGMEM = "width: calc(100% - 100px);";
const char line317[] PROGMEM = "}";
const char line318[] PROGMEM = "";
const char line319[] PROGMEM = ".wrap {";
const char line320[] PROGMEM = "--dif: calc(var(--max) - var(--min));";
const char line321[] PROGMEM = "display: grid;";
const char line322[] PROGMEM = "grid-template: repeat(2, max-content) 2em/1fr 1fr;";
const char line323[] PROGMEM = "overflow: hidden;";
const char line324[] PROGMEM = "position: relative;";
const char line325[] PROGMEM = "margin: 1em auto;";
const char line326[] PROGMEM = "width: 100%;";
const char line327[] PROGMEM = "background: linear-gradient(0deg, #ccc 2em, transparent 0);";
const char line328[] PROGMEM = "font-family: ubuntu mono, consolas, monaco, monospace;";
const char line329[] PROGMEM = "}";
const char line330[] PROGMEM = ".wrap::before, .wrap::after {";
const char line331[] PROGMEM = "grid-column: 1/span 2;";
const char line332[] PROGMEM = "grid-row: 3;";
const char line333[] PROGMEM = "height: 100%;";
const char line334[] PROGMEM = "background: rgb(123, 202, 123);";
const char line335[] PROGMEM = "content: \"\";";
const char line336[] PROGMEM = "}";
const char line337[] PROGMEM = ".wrap::before {";
const char line338[] PROGMEM = "margin-left: calc((var(--a) - var(--min))/var(--dif)*100%);";
const char line339[] PROGMEM = "width: calc((var(--b) - var(--a))/var(--dif)*100%);";
const char line340[] PROGMEM = "}";
const char line341[] PROGMEM = ".wrap::after {";
const char line342[] PROGMEM = "margin-left: calc((var(--b) - var(--min))/var(--dif)*100%);";
const char line343[] PROGMEM = "width: calc((var(--a) - var(--b))/var(--dif)*100%);";
const char line344[] PROGMEM = "}";
const char line345[] PROGMEM = "";
const char line346[] PROGMEM = "[id=multi-lbl] {";
const char line347[] PROGMEM = "grid-column: 1/span 2;";
const char line348[] PROGMEM = "}";
const char line349[] PROGMEM = "";
const char line350[] PROGMEM = ".sr-only {";
const char line351[] PROGMEM = "position: absolute;";
const char line352[] PROGMEM = "clip-path: inset(50%);";
const char line353[] PROGMEM = "}";
const char line354[] PROGMEM = "";
const char line355[] PROGMEM = "input.twoThumbSlider[type=range] {";
const char line356[] PROGMEM = "grid-column: 1/span 2;";
const char line357[] PROGMEM = "grid-row: 3;";
const char line358[] PROGMEM = "z-index: 1;";
const char line359[] PROGMEM = "top: 0;";
const char line360[] PROGMEM = "left: 0;";
const char line361[] PROGMEM = "margin: 0;";
const char line362[] PROGMEM = "background: none;";
const char line363[] PROGMEM = "/* get rid of white Chrome background */";
const char line364[] PROGMEM = "color: #000;";
const char line365[] PROGMEM = "pointer-events: none;";
const char line366[] PROGMEM = "}";
const char line367[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-runnable-track, input[type=range]::-webkit-slider-thumb, input[type=range] {";
const char line368[] PROGMEM = "-webkit-appearance: none;";
const char line369[] PROGMEM = "}";
const char line370[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-runnable-track {";
const char line371[] PROGMEM = "width: 100%;";
const char line372[] PROGMEM = "height: 100%;";
const char line373[] PROGMEM = "background: none;";
const char line374[] PROGMEM = "}";
const char line375[] PROGMEM = "input.twoThumbSlider[type=range]::-moz-range-track {";
const char line376[] PROGMEM = "width: 100%;";
const char line377[] PROGMEM = "height: 100%;";
const char line378[] PROGMEM = "background: none;";
const char line379[] PROGMEM = "}";
const char line380[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-thumb {";
const char line381[] PROGMEM = "border: none;";
const char line382[] PROGMEM = "/* get rid of Firefox thumb border */";
const char line383[] PROGMEM = "width: 2em;";
const char line384[] PROGMEM = "height: 100%;";
const char line385[] PROGMEM = "border-radius: 0;";
const char line386[] PROGMEM = "/* get rid of Firefox corner rounding */";
const char line387[] PROGMEM = "background: currentcolor;";
const char line388[] PROGMEM = "pointer-events: auto;";
const char line389[] PROGMEM = "}";
const char line390[] PROGMEM = "input.twoThumbSlider[type=range]::-moz-range-thumb {";
const char line391[] PROGMEM = "border: none;";
const char line392[] PROGMEM = "/* get rid of Firefox thumb border */";
const char line393[] PROGMEM = "width: 2em;";
const char line394[] PROGMEM = "height: 2em;";
const char line395[] PROGMEM = "border-radius: 0;";
const char line396[] PROGMEM = "/* get rid of Firefox corner rounding */";
const char line397[] PROGMEM = "background: currentcolor;";
const char line398[] PROGMEM = "pointer-events: auto;";
const char line399[] PROGMEM = "}";
const char line400[] PROGMEM = "input.twoThumbSlider[type=range]:focus {";
const char line401[] PROGMEM = "z-index: 2;";
const char line402[] PROGMEM = "outline: dotted 1px currentcolor;";
const char line403[] PROGMEM = "}";
const char line404[] PROGMEM = "input.twoThumbSlider[type=range]:focus, input[type=range]:focus + output {";
const char line405[] PROGMEM = "color: darkorange;";
const char line406[] PROGMEM = "}";
const char line407[] PROGMEM = "";
const char line408[] PROGMEM = "output.twoThumbSlider {";
const char line409[] PROGMEM = "grid-row: 2;";
const char line410[] PROGMEM = "}";
const char line411[] PROGMEM = "output.twoThumbSlider:last-child {";
const char line412[] PROGMEM = "text-align: right;";
const char line413[] PROGMEM = "}";
const char line414[] PROGMEM = "output.twoThumbSlider::after {";
const char line415[] PROGMEM = "counter-reset: c var(--c);";
const char line416[] PROGMEM = "content: \"--\" attr(for) \": \" counter(c) \";\";";
const char line417[] PROGMEM = "}";
const char line418[] PROGMEM = "";
const char line419[] PROGMEM = "</style>";
const char line420[] PROGMEM = "</head>";
const char line421[] PROGMEM = "";
const char line422[] PROGMEM = "";
const char line423[] PROGMEM = "";
const char line424[] PROGMEM = "";
const char line425[] PROGMEM = "<!--<body onload=\"GetArduinoIO()\">-->";
const char line426[] PROGMEM = "<body>";
const char line427[] PROGMEM = "<h1>MoBa Licht Steuerung</h1>";
const char line428[] PROGMEM = "<br>";
const char line429[] PROGMEM = "<button class=\"button\" id=\"office_table_ww_button\" onclick=\"LightSceneButtonPushed(LightScene.OFFICE_TABLE_WW, this)\">B&uuml;rotisch</button>";
const char line430[] PROGMEM = "<button class=\"button\" id=\"light_on_ww_button\" onclick=\"LightSceneButtonPushed(LightScene.LIGHT_ON_WW, this)\">Licht warm Weiss</button>";
const char line431[] PROGMEM = "<button class=\"button\" id=\"disco_button\" onclick=\"LightSceneButtonPushed(LightScene.DISCO, this)\">Disco</button>";
const char line432[] PROGMEM = "<button class=\"button\" id=\"sunset_button\" onclick=\"LightSceneButtonPushed(LightScene.SUNSET, this)\">Sunset</button>";
const char line433[] PROGMEM = "<button class=\"button\" id=\"sunrise_button\" onclick=\"LightSceneButtonPushed(LightScene.SUNRISE, this)\">Sunrise</button>";
const char line434[] PROGMEM = "<button class=\"button\" id=\"power_off\" onclick=\"LightSceneButtonPushed(LightScene.POWER_OFF, this)\">Power Off</button>";
const char line435[] PROGMEM = "<br>";
const char line436[] PROGMEM = "<br>";
const char line437[] PROGMEM = "<br>";
const char line438[] PROGMEM = "";
const char line439[] PROGMEM = "<h2>Helligkeit einstellen</h2>";
const char line440[] PROGMEM = "<br>";
const char line441[] PROGMEM = "<div class=\"slidecontainer\">";
const char line442[] PROGMEM = "<label for=\"brightness_value\">Helligkeit</label>";
const char line443[] PROGMEM = "<label id=\"brightness_value\"></label>";
const char line444[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"brightness_slider\" oninput=\"BrighntessSliderChanged()\" style=\"background:rgb(255, 240, 27)\">";
const char line445[] PROGMEM = "</div>";
const char line446[] PROGMEM = "<br>";
const char line447[] PROGMEM = "<br>";
const char line448[] PROGMEM = "";
const char line449[] PROGMEM = "<h2>Leuchtposition</h2>";
const char line450[] PROGMEM = "<table style=\"width: 100%\">";
const char line451[] PROGMEM = "<tr>";
const char line452[] PROGMEM = "<td>";
const char line453[] PROGMEM = "<label for=\"led_row\">Reihen</label>";
const char line454[] PROGMEM = "<label type=\"text\" id=\"led_row\" readonly style=\"border:0; color:#f6931f; font-weight:bold;\"></label>";
const char line455[] PROGMEM = "</td>";
const char line456[] PROGMEM = "<td>";
const char line457[] PROGMEM = "<label for=\"led_column\">L&auml;nge</label>";
const char line458[] PROGMEM = "<label type=\"text\" id=\"led_column\" readonly style=\"border:0; color:#f6931f; font-weight:bold;\"></label>";
const char line459[] PROGMEM = "</td>";
const char line460[] PROGMEM = "</tr>";
const char line461[] PROGMEM = "<tr>";
const char line462[] PROGMEM = "<td id=\"led_slider_row\">";
const char line463[] PROGMEM = "<!--<div style=\"transform: rotate(270deg);\">-->";
const char line464[] PROGMEM = "<div>";
const char line465[] PROGMEM = "<div id=\"slider_row\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: 0; --b: 3; --min: 0; --max: 3;\">";
const char line466[] PROGMEM = "<!--<div id=\"multi-lbl\">Multi thumb slider: 0 - 15</div>-->";
const char line467[] PROGMEM = "<input id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"0\" max=\"3\" />";
const char line468[] PROGMEM = "<!--<output for=\"a\" style=\"--c: var(--a)\"></output>-->";
const char line469[] PROGMEM = "<input id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"3\" max=\"3\" />";
const char line470[] PROGMEM = "<!--<output for=\"b\" style=\"--c: var(--b)\"></output>-->";
const char line471[] PROGMEM = "</div>";
const char line472[] PROGMEM = "</td>";
const char line473[] PROGMEM = "<td id=led_slider_column>";
const char line474[] PROGMEM = "<div id=\"slider_columen\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: 20; --b: 120; --min: 0; --max: 284\">";
const char line475[] PROGMEM = "<!--<div id=\"multi-lbl\">Multi thumb slider: 0 - 15</div>-->";
const char line476[] PROGMEM = "<input id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"20\" max=\"284\" />";
const char line477[] PROGMEM = "<!--<output for=\"a\" style=\"--c: var(--a)\"></output>-->";
const char line478[] PROGMEM = "<input id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"120\" max=\"284\" />";
const char line479[] PROGMEM = "<!--<output for=\"b\" style=\"--c: var(--b)\"></output>-->";
const char line480[] PROGMEM = "</div>";
const char line481[] PROGMEM = "</td>";
const char line482[] PROGMEM = "</tr>";
const char line483[] PROGMEM = "</table>";
const char line484[] PROGMEM = "</body>";
const char line485[] PROGMEM = "</html>";

const char* const website_a[] PROGMEM = {line1, line2, line3, line4, line5, line6, line7, line8, line9, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, line21, line22, line23, line24, line25, line26, line27, line28, line29, line30, line31, line32, line33, line34, line35, line36, line37, line38, line39, line40, line41, line42, line43, line44, line45, line46, line47, line48, line49, line50, line51, line52, line53, line54, line55, line56, line57, line58, line59, line60, line61, line62, line63, line64, line65, line66, line67, line68, line69, line70, line71, line72, line73, line74, line75, line76, line77, line78, line79, line80, line81, line82, line83, line84, line85, line86, line87, line88, line89, line90, line91, line92, line93, line94, line95, line96, line97, line98, line99, line100, line101, line102, line103, line104, line105, line106, line107, line108, line109, line110, line111, line112, line113, line114, line115, line116, line117, line118, line119, line120, line121, line122, line123, line124, line125, line126, line127, line128, line129, line130, line131, line132, line133, line134, line135, line136, line137, line138, line139, line140, line141, line142, line143, line144, line145, line146, line147, line148, line149, line150, line151, line152, line153, line154, line155, line156, line157, line158, line159, line160, line161, line162, line163, line164, line165, line166, line167, line168, line169, line170, line171, line172, line173, line174, line175, line176, line177, line178, line179, line180, line181, line182, line183, line184, line185, line186, line187, line188, line189, line190, line191, line192, line193, line194, line195, line196, line197, line198, line199, line200, line201, line202, line203, line204, line205, line206, line207, line208, line209, line210, line211, line212, line213, line214, line215, line216, line217, line218, line219, line220, line221, line222, line223, line224, line225, line226, line227, line228, line229, line230, line231, line232, line233, line234, line235, line236, line237, line238, line239, line240, line241, line242, line243, line244, line245, line246, line247, line248, line249, line250, line251, line252, line253, line254, line255, line256, line257, line258, line259, line260, line261, line262, line263, line264, line265, line266, line267, line268, line269, line270, line271, line272, line273, line274, line275, line276, line277, line278, line279, line280, line281, line282, line283, line284, line285, line286, line287, line288, line289, line290, line291, line292, line293, line294, line295, line296, line297, line298, line299, line300, line301, line302, line303, line304, line305, line306, line307, line308, line309, line310, line311, line312, line313, line314, line315, line316, line317, line318, line319, line320, line321, line322, line323, line324, line325, line326, line327, line328, line329, line330, line331, line332, line333, line334, line335, line336, line337, line338, line339, line340, line341, line342, line343, line344, line345, line346, line347, line348, line349, line350, line351, line352, line353, line354, line355, line356, line357, line358, line359, line360, line361, line362, line363, line364, line365, line366, line367, line368, line369, line370, line371, line372, line373, line374, line375, line376, line377, line378, line379, line380, line381, line382, line383, line384, line385, line386, line387, line388, line389, line390, line391, line392, line393, line394, line395, line396, line397, line398, line399, line400, line401, line402, line403, line404, line405, line406, line407, line408, line409, line410, line411, line412, line413, line414, line415, line416, line417, line418, line419, line420, line421, line422, line423, line424, line425, line426, line427, line428, line429, line430, line431, line432, line433, line434, line435, line436, line437, line438, line439, line440, line441, line442, line443, line444, line445, line446, line447, line448, line449, line450, line451, line452, line453, line454, line455, line456, line457, line458, line459, line460, line461, line462, line463, line464, line465, line466, line467, line468, line469, line470, line471, line472, line473, line474, line475, line476, line477, line478, line479, line480, line481, line482, line483, line484, line485};


//-----------------------------------------------------------------------------
// define
#define WEBSITE_NOF_LINES 485


//-----------------------------------------------------------------------------
// static module variable



//*****************************************************************************
// description:
//   Website_SendToClient
//*****************************************************************************
void Website_SendToClient(EthernetClient client)
{
	uint32_t line = 0;
    char line_str[179];

	for (line = 0; line < WEBSITE_NOF_LINES; line++)
	{
        strcpy_P(line_str, (char*)pgm_read_word(&(website_a[line])));
		client.println(line_str);
	}
}
