/*******************************************************************************
Project   RoomLight

  This is an OpenSource Project.
  You can use, share or improve this project. If you improve this source code
  please share with the comunity or at least with the author of the original
  source code

  Created 29. October 2021 by MarkusNTrains
================================================================================
$HeadURL:  $
$Id:  $
*******************************************************************************/


//-----------------------------------------------------------------------------
// includes
#include "Website.h"


//-----------------------------------------------------------------------------
// PROGMEM -> store data in flash
const char line1[] PROGMEM = "<!-- html realtime: https://htmledit.squarefree.com/-->";
const char line2[] PROGMEM = "<!DOCTYPE HTML>";
const char line3[] PROGMEM = "<html lang=\"en\">";
const char line4[] PROGMEM = "<head>";
const char line5[] PROGMEM = "<meta charset=\"utf-8\">";
const char line6[] PROGMEM = "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
const char line7[] PROGMEM = "<title>MoBa Room Light</title>";
const char line8[] PROGMEM = "<link rel=\"icon\" href=\"favicon.ico\">";
const char line9[] PROGMEM = "<script type=\"text/javascript\" charset=\"utf-8\">";
const char line10[] PROGMEM = "//--- const ------------------------------------------------------";
const char line11[] PROGMEM = "const LightScene =";
const char line12[] PROGMEM = "{";
const char line13[] PROGMEM = "OFFICE_TABLE: 0,";
const char line14[] PROGMEM = "LIGHT_ON: 1,";
const char line15[] PROGMEM = "RAINBOW: 2,";
const char line16[] PROGMEM = "SUNSET: 3,";
const char line17[] PROGMEM = "SUNRISE: 4,";
const char line18[] PROGMEM = "POWER_OFF: 5,";
const char line19[] PROGMEM = "DISCO: 6,";
const char line20[] PROGMEM = "SBH: 7,";
const char line21[] PROGMEM = "USER_SETTING: 8,";
const char line22[] PROGMEM = "IDLE: 9,";
const char line23[] PROGMEM = "LIGHTNING: 10,";
const char line24[] PROGMEM = "MOBA: 11,";
const char line25[] PROGMEM = "DAY: 12,";
const char line26[] PROGMEM = "NIGHT: 13,";
const char line27[] PROGMEM = "NOF: 14";
const char line28[] PROGMEM = "};";
const char line29[] PROGMEM = "";
const char line30[] PROGMEM = "const XML_RREQUEST =";
const char line31[] PROGMEM = "{";
const char line32[] PROGMEM = "GetCurrentData: \"GetCurrentData\",";
const char line33[] PROGMEM = "SetArea: \"SetArea\",";
const char line34[] PROGMEM = "SetBrightness: \"SetBrightness\",";
const char line35[] PROGMEM = "SetColor: \"SetColor\",";
const char line36[] PROGMEM = "SetLightScene: \"LightScene\",";
const char line37[] PROGMEM = "};";
const char line38[] PROGMEM = "";
const char line39[] PROGMEM = "const SEND_DATA_TO_ARDUINO_LOCK_TIMEOUT_MS = 2000;";
const char line40[] PROGMEM = "";
const char line41[] PROGMEM = "";
const char line42[] PROGMEM = "//--- static variables --------------------------------------------";
const char line43[] PROGMEM = "var s_lock_send_data = false;";
const char line44[] PROGMEM = "var s_is_send_data_pending = false;";
const char line45[] PROGMEM = "var s_pending_xml_request = \"\";";
const char line46[] PROGMEM = "var s_sendToArduino_timeoutTimer = null;";
const char line47[] PROGMEM = "var s_requestDataFromArduino_intervallTimer = null;";
const char line48[] PROGMEM = "var xhttp = null;";
const char line49[] PROGMEM = "";
const char line50[] PROGMEM = "";
const char line51[] PROGMEM = "//--- onload event handler ----------------------------------------";
const char line52[] PROGMEM = "window.addEventListener('load', (event) =>";
const char line53[] PROGMEM = "{";
const char line54[] PROGMEM = "var button = '<button class=\"button\" id=\"LightScene' + LightScene.POWER_OFF + '\" onclick=\"LightSceneButtonPushed(LightScene.POWER_OFF, this)\">Off</button>'";
const char line55[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.OFFICE_TABLE + '\" onclick=\"LightSceneButtonPushed(LightScene.OFFICE_TABLE, this)\">B&uuml;rotisch</button>'";
const char line56[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.MOBA + '\" onclick=\"LightSceneButtonPushed(LightScene.MOBA, this)\">MoBa</button>'";
const char line57[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.LIGHT_ON + '\" onclick=\"LightSceneButtonPushed(LightScene.LIGHT_ON, this)\">All On</button>'";
const char line58[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.RAINBOW + '\" onclick=\"LightSceneButtonPushed(LightScene.RAINBOW, this)\">Rainbow</button>'";
const char line59[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.DISCO + '\" onclick=\"LightSceneButtonPushed(LightScene.DISCO, this)\">Disco</button>'";
const char line60[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.USER_SETTING + '\" onclick=\"LightSceneButtonPushed(LightScene.USER_SETTING, this)\">User Set</button>'";
const char line61[] PROGMEM = "+ '<br>'";
const char line62[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.SUNRISE + '\" onclick=\"LightSceneButtonPushed(LightScene.SUNRISE, this)\">Sunrise</button>'";
const char line63[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.DAY + '\" onclick=\"LightSceneButtonPushed(LightScene.DAY, this)\">Day</button>'";
const char line64[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.SUNSET + '\" onclick=\"LightSceneButtonPushed(LightScene.SUNSET, this)\">Sunset</button>'";
const char line65[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.NIGHT + '\" onclick=\"LightSceneButtonPushed(LightScene.NIGHT, this)\">Night</button>'";
const char line66[] PROGMEM = "+ '<button class=\"button\" id=\"LightScene' + LightScene.LIGHTNING + '\" onclick=\"LightSceneButtonPushed(LightScene.LIGHTNING, this)\">Gewitter</button>';";
const char line67[] PROGMEM = "";
const char line68[] PROGMEM = "document.getElementById(\"LightScene\").innerHTML = button;";
const char line69[] PROGMEM = "";
const char line70[] PROGMEM = "RequestCurrentDataFromArduino();";
const char line71[] PROGMEM = "});";
const char line72[] PROGMEM = "";
const char line73[] PROGMEM = "";
const char line74[] PROGMEM = "//--- function ----------------------------------------------------";
const char line75[] PROGMEM = "function RequestCurrentDataFromArduino()";
const char line76[] PROGMEM = "{";
const char line77[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.GetCurrentData);";
const char line78[] PROGMEM = "}";
const char line79[] PROGMEM = "";
const char line80[] PROGMEM = "function Reset_RequestCurrentDataFromArduino_IntervallTimer()";
const char line81[] PROGMEM = "{";
const char line82[] PROGMEM = "clearInterval(s_requestDataFromArduino_intervallTimer);";
const char line83[] PROGMEM = "s_requestDataFromArduino_intervallTimer = setInterval(RequestCurrentDataFromArduino, SEND_DATA_TO_ARDUINO_LOCK_TIMEOUT_MS + 500);";
const char line84[] PROGMEM = "}";
const char line85[] PROGMEM = "";
const char line86[] PROGMEM = "function ReleaseLock()";
const char line87[] PROGMEM = "{";
const char line88[] PROGMEM = "s_lock_send_data = false;";
const char line89[] PROGMEM = "s_sendToArduino_timeoutTimer = null;";
const char line90[] PROGMEM = "";
const char line91[] PROGMEM = "if (xhttp != null)";
const char line92[] PROGMEM = "{";
const char line93[] PROGMEM = "xhttp.abort();";
const char line94[] PROGMEM = "xhttp = null;";
const char line95[] PROGMEM = "}";
const char line96[] PROGMEM = "";
const char line97[] PROGMEM = "if (s_is_send_data_pending == true)";
const char line98[] PROGMEM = "{";
const char line99[] PROGMEM = "SendDataToArduino(s_pending_xml_request);";
const char line100[] PROGMEM = "s_is_send_data_pending = false;";
const char line101[] PROGMEM = "s_pending_xml_request = \"\";";
const char line102[] PROGMEM = "}";
const char line103[] PROGMEM = "}";
const char line104[] PROGMEM = "";
const char line105[] PROGMEM = "function SendDataToArduino(xml_request)";
const char line106[] PROGMEM = "{";
const char line107[] PROGMEM = "if (s_lock_send_data == false)";
const char line108[] PROGMEM = "{";
const char line109[] PROGMEM = "s_lock_send_data = true;";
const char line110[] PROGMEM = "Reset_RequestCurrentDataFromArduino_IntervallTimer();";
const char line111[] PROGMEM = "nocache = \"&nocache=\" + Math.random() * 1000000;";
const char line112[] PROGMEM = "";
const char line113[] PROGMEM = "xhttp = new XMLHttpRequest();";
const char line114[] PROGMEM = "xhttp.onreadystatechange = function()";
const char line115[] PROGMEM = "{";
const char line116[] PROGMEM = "if (this.readyState == XMLHttpRequest.DONE)";
const char line117[] PROGMEM = "{";
const char line118[] PROGMEM = "if (this.status == 200)";
const char line119[] PROGMEM = "{";
const char line120[] PROGMEM = "if (this.responseXML != null)";
const char line121[] PROGMEM = "{";
const char line122[] PROGMEM = "// XML file received - contains LED states";
const char line123[] PROGMEM = "var re = this.responseXML.getElementsByTagName('scene');";
const char line124[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line125[] PROGMEM = "{";
const char line126[] PROGMEM = "LightScene_ShowAsActive(re[0].childNodes[0].nodeValue);";
const char line127[] PROGMEM = "}";
const char line128[] PROGMEM = "";
const char line129[] PROGMEM = "re = this.responseXML.getElementsByTagName('brightness');";
const char line130[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line131[] PROGMEM = "{";
const char line132[] PROGMEM = "document.getElementById(\"brightness_slider\").value = re[0].childNodes[0].nodeValue;";
const char line133[] PROGMEM = "document.getElementById(\"brightness_value\").innerHTML = re[0].childNodes[0].nodeValue;";
const char line134[] PROGMEM = "}";
const char line135[] PROGMEM = "";
const char line136[] PROGMEM = "re = this.responseXML.getElementsByTagName('brightness');";
const char line137[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line138[] PROGMEM = "{";
const char line139[] PROGMEM = "document.getElementById(\"brightness_slider\").value = re[0].childNodes[0].nodeValue;";
const char line140[] PROGMEM = "document.getElementById(\"brightness_value\").innerHTML = re[0].childNodes[0].nodeValue;";
const char line141[] PROGMEM = "}";
const char line142[] PROGMEM = "";
const char line143[] PROGMEM = "re = this.responseXML.getElementsByTagName('color');";
const char line144[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line145[] PROGMEM = "{";
const char line146[] PROGMEM = "var color = parseInt(re[0].childNodes[0].nodeValue);";
const char line147[] PROGMEM = "if (color > 0xFFFFFF)";
const char line148[] PROGMEM = "{";
const char line149[] PROGMEM = "color = (color >> 24) & 0xFF;";
const char line150[] PROGMEM = "document.getElementById(\"color_white_slider\").value = color;";
const char line151[] PROGMEM = "document.getElementById(\"color_white_value\").innerHTML = color;";
const char line152[] PROGMEM = "colorStr = ('000000' + ((color << 16) | (color << 8) | color).toString(16)).slice(-6);";
const char line153[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line154[] PROGMEM = "}";
const char line155[] PROGMEM = "else";
const char line156[] PROGMEM = "{";
const char line157[] PROGMEM = "var slider_value = 0;";
const char line158[] PROGMEM = "if (((color >= 0xFF0000) && (color <= 0xFFFF00)) && (((color & 0xFF0000) == 0xFF0000) && (((color & 0xFF) == 0x0))))";
const char line159[] PROGMEM = "{";
const char line160[] PROGMEM = "slider_value = ((color & 0xFF00) >> 8);";
const char line161[] PROGMEM = "}";
const char line162[] PROGMEM = "else if (((color >= 0x00FF00) && (color <= 0xFFFF00)) && (((color & 0xFF00) == 0xFF00) && (((color & 0xFF) == 0x0))))";
const char line163[] PROGMEM = "{";
const char line164[] PROGMEM = "slider_value = 511 - ((color & 0xFF0000) >> 16);";
const char line165[] PROGMEM = "}";
const char line166[] PROGMEM = "else if (((color >= 0x00FF00) && (color <= 0x00FFFF)) && (((color & 0xFF00) == 0xFF00) && (((color & 0xFF0000) == 0x0))))";
const char line167[] PROGMEM = "{";
const char line168[] PROGMEM = "slider_value = 512 + (color & 0xFF);";
const char line169[] PROGMEM = "}";
const char line170[] PROGMEM = "else if (((color >= 0x0000FF) && (color <= 0x00FFFF)) && (((color & 0xFF) == 0xFF) && (((color & 0xFF0000) == 0x0))))";
const char line171[] PROGMEM = "{";
const char line172[] PROGMEM = "slider_value = 1023 - ((color & 0x00FF00) >> 8);";
const char line173[] PROGMEM = "}";
const char line174[] PROGMEM = "else if (((color >= 0x0000FF) && (color <= 0xFF00FF)) && (((color & 0xFF) == 0xFF) && (((color & 0xFF00) == 0x0))))";
const char line175[] PROGMEM = "{";
const char line176[] PROGMEM = "slider_value = 1024 + ((color & 0xFF0000) >> 16);";
const char line177[] PROGMEM = "}";
const char line178[] PROGMEM = "else if (((color >= 0xFF0000) && (color <= 0xFF00FF)) && (((color & 0xFF0000) == 0xFF0000) && (((color & 0xFF00) == 0x0))))";
const char line179[] PROGMEM = "{";
const char line180[] PROGMEM = "slider_value = 1535 - (color & 0xFF);";
const char line181[] PROGMEM = "}";
const char line182[] PROGMEM = "";
const char line183[] PROGMEM = "var colorStr = ('000000' + color.toString(16)).slice(-6);";
const char line184[] PROGMEM = "document.getElementById(\"color_rgb_slider\").value = slider_value;";
const char line185[] PROGMEM = "document.getElementById(\"color_rgb_value\").innerHTML = '0x' + colorStr;;";
const char line186[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line187[] PROGMEM = "}";
const char line188[] PROGMEM = "}";
const char line189[] PROGMEM = "";
const char line190[] PROGMEM = "re = this.responseXML.getElementsByTagName('led_area');";
const char line191[] PROGMEM = "if ((re != undefined) && (re != null) && (re.length > 0))";
const char line192[] PROGMEM = "{";
const char line193[] PROGMEM = "var xs = this.responseXML.getElementsByTagName('xs')[0].childNodes[0].nodeValue;";
const char line194[] PROGMEM = "var xe = this.responseXML.getElementsByTagName('xe')[0].childNodes[0].nodeValue;";
const char line195[] PROGMEM = "var ys = this.responseXML.getElementsByTagName('ys')[0].childNodes[0].nodeValue;";
const char line196[] PROGMEM = "var ye = this.responseXML.getElementsByTagName('ye')[0].childNodes[0].nodeValue;";
const char line197[] PROGMEM = "";
const char line198[] PROGMEM = "document.getElementById(\"led_column\").innerHTML = (xs + \" - \" + xe);";
const char line199[] PROGMEM = "document.getElementById(\"led_row\").innerHTML = (ys + \" - \" + ye);";
const char line200[] PROGMEM = "";
const char line201[] PROGMEM = "/*document.getElementById(\"slider_columen\").style.setProperty(\"--a\", xs);";
const char line202[] PROGMEM = "document.getElementById(\"slider_columen\").style.setProperty(\"--b\", xe);";
const char line203[] PROGMEM = "document.getElementById(\"slider_row\").style.setProperty(\"--a\", ys);";
const char line204[] PROGMEM = "document.getElementById(\"slider_row\").style.setProperty(\"--b\", ye);*/";
const char line205[] PROGMEM = "}";
const char line206[] PROGMEM = "";
const char line207[] PROGMEM = "";
const char line208[] PROGMEM = "if (s_sendToArduino_timeoutTimer != null)";
const char line209[] PROGMEM = "{";
const char line210[] PROGMEM = "clearTimeout(s_sendToArduino_timeoutTimer);";
const char line211[] PROGMEM = "ReleaseLock();";
const char line212[] PROGMEM = "}";
const char line213[] PROGMEM = "}";
const char line214[] PROGMEM = "else";
const char line215[] PROGMEM = "{";
const char line216[] PROGMEM = "alert(\"XML = NULL\");";
const char line217[] PROGMEM = "}";
const char line218[] PROGMEM = "}";
const char line219[] PROGMEM = "else";
const char line220[] PROGMEM = "{";
const char line221[] PROGMEM = "//alert(\"Keine Verbindung zum Webserver\\nStatus: \" + this.status);";
const char line222[] PROGMEM = "}";
const char line223[] PROGMEM = "}";
const char line224[] PROGMEM = "}";
const char line225[] PROGMEM = "";
const char line226[] PROGMEM = "// send HTTP GET request with LEDs to switch on/off if any";
const char line227[] PROGMEM = "xhttp.open(\"GET\", \"ajax_inputs\" + xml_request + nocache, true);";
const char line228[] PROGMEM = "xhttp.send();";
const char line229[] PROGMEM = "";
const char line230[] PROGMEM = "// lock Send to Arduino";
const char line231[] PROGMEM = "s_sendToArduino_timeoutTimer = setTimeout('ReleaseLock()', SEND_DATA_TO_ARDUINO_LOCK_TIMEOUT_MS);";
const char line232[] PROGMEM = "}";
const char line233[] PROGMEM = "else";
const char line234[] PROGMEM = "{";
const char line235[] PROGMEM = "s_is_send_data_pending = true;";
const char line236[] PROGMEM = "s_pending_xml_request = xml_request;";
const char line237[] PROGMEM = "}";
const char line238[] PROGMEM = "}";
const char line239[] PROGMEM = "";
const char line240[] PROGMEM = "function LightSceneButtonPushed(scene, bt)";
const char line241[] PROGMEM = "{";
const char line242[] PROGMEM = "LightScene_ShowAsActive(scene)";
const char line243[] PROGMEM = "var brightness = document.getElementById(\"brightness_slider\").value;";
const char line244[] PROGMEM = "if (brightness == 0)";
const char line245[] PROGMEM = "{";
const char line246[] PROGMEM = "brightness = 100;";
const char line247[] PROGMEM = "}";
const char line248[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.SetLightScene + \"=\" + scene + \"&\" + XML_RREQUEST.SetBrightness + \"=\" + brightness);";
const char line249[] PROGMEM = "}";
const char line250[] PROGMEM = "";
const char line251[] PROGMEM = "function LightScene_ShowAsActive(scene)";
const char line252[] PROGMEM = "{";
const char line253[] PROGMEM = "var matches = document.getElementsByClassName('active-class');";
const char line254[] PROGMEM = "for (var cnt = 0; cnt < matches.length; cnt++)";
const char line255[] PROGMEM = "{";
const char line256[] PROGMEM = "matches[cnt].classList.remove('active-class');";
const char line257[] PROGMEM = "}";
const char line258[] PROGMEM = "";
const char line259[] PROGMEM = "if (scene < LightScene.NOF)";
const char line260[] PROGMEM = "{";
const char line261[] PROGMEM = "document.getElementById(\"LightScene\" + scene).classList.add(\"active-class\");";
const char line262[] PROGMEM = "}";
const char line263[] PROGMEM = "}";
const char line264[] PROGMEM = "";
const char line265[] PROGMEM = "function BrighntessSliderChanged()";
const char line266[] PROGMEM = "{";
const char line267[] PROGMEM = "var slider = document.getElementById(\"brightness_slider\");";
const char line268[] PROGMEM = "var output = document.getElementById(\"brightness_value\");";
const char line269[] PROGMEM = "output.innerHTML = slider.value;";
const char line270[] PROGMEM = "";
const char line271[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.SetBrightness + \"=\" + slider.value);";
const char line272[] PROGMEM = "}";
const char line273[] PROGMEM = "";
const char line274[] PROGMEM = "function ColorRGBSliderChanged()";
const char line275[] PROGMEM = "{";
const char line276[] PROGMEM = "var slider = document.getElementById(\"color_rgb_slider\");";
const char line277[] PROGMEM = "var output = document.getElementById(\"color_rgb_value\");";
const char line278[] PROGMEM = "";
const char line279[] PROGMEM = "var color = 0;";
const char line280[] PROGMEM = "if (slider.value > 1279)";
const char line281[] PROGMEM = "{";
const char line282[] PROGMEM = "color = 0xFF00FF - (slider.value - 1280);";
const char line283[] PROGMEM = "}";
const char line284[] PROGMEM = "else if (slider.value > 1023)";
const char line285[] PROGMEM = "{";
const char line286[] PROGMEM = "color = 0x0000FF + ((slider.value - 1024) << 16);";
const char line287[] PROGMEM = "}";
const char line288[] PROGMEM = "else if (slider.value > 767)";
const char line289[] PROGMEM = "{";
const char line290[] PROGMEM = "color = 0x00FFFF - ((slider.value - 768) << 8);";
const char line291[] PROGMEM = "}";
const char line292[] PROGMEM = "else if (slider.value > 511)";
const char line293[] PROGMEM = "{";
const char line294[] PROGMEM = "color = 0x00FF00 + (slider.value - 512);";
const char line295[] PROGMEM = "}";
const char line296[] PROGMEM = "else if (slider.value > 255)";
const char line297[] PROGMEM = "{";
const char line298[] PROGMEM = "color = 0xFFFF00 - ((slider.value - 256) << 16);";
const char line299[] PROGMEM = "}";
const char line300[] PROGMEM = "else";
const char line301[] PROGMEM = "{";
const char line302[] PROGMEM = "color = 0xFF0000 + (slider.value << 8);";
const char line303[] PROGMEM = "}";
const char line304[] PROGMEM = "";
const char line305[] PROGMEM = "var colorStr = ('000000' + color.toString(16)).slice(-6);";
const char line306[] PROGMEM = "output.innerHTML = '0x' + colorStr;";
const char line307[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line308[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.SetColor + \"=\" + color);";
const char line309[] PROGMEM = "}";
const char line310[] PROGMEM = "";
const char line311[] PROGMEM = "function ColorRGBSingleSliderChanged()";
const char line312[] PROGMEM = "{";
const char line313[] PROGMEM = "var red_slider = document.getElementById(\"color_red_slider\");";
const char line314[] PROGMEM = "var green_slider = document.getElementById(\"color_green_slider\");";
const char line315[] PROGMEM = "var blue_slider = document.getElementById(\"color_blue_slider\");";
const char line316[] PROGMEM = "";
const char line317[] PROGMEM = "document.getElementById(\"color_red_value\").innerHTML = red_slider.value;";
const char line318[] PROGMEM = "document.getElementById(\"color_green_value\").innerHTML = green_slider.value;";
const char line319[] PROGMEM = "document.getElementById(\"color_blue_value\").innerHTML = blue_slider.value;";
const char line320[] PROGMEM = "";
const char line321[] PROGMEM = "var color = 0;";
const char line322[] PROGMEM = "color = (red_slider.value << 16);";
const char line323[] PROGMEM = "color |= (green_slider.value << 8);";
const char line324[] PROGMEM = "color |= blue_slider.value";
const char line325[] PROGMEM = "";
const char line326[] PROGMEM = "var colorStr = ('000000' + color.toString(16)).slice(-6);";
const char line327[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line328[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.SetColor + \"=\" + color);";
const char line329[] PROGMEM = "}";
const char line330[] PROGMEM = "";
const char line331[] PROGMEM = "function ColorWhiteSliderChanged()";
const char line332[] PROGMEM = "{";
const char line333[] PROGMEM = "var slider = document.getElementById(\"color_white_slider\");";
const char line334[] PROGMEM = "var output = document.getElementById(\"color_white_value\");";
const char line335[] PROGMEM = "";
const char line336[] PROGMEM = "var color = slider.value;";
const char line337[] PROGMEM = "output.innerHTML = color;";
const char line338[] PROGMEM = "colorStr = ('000000' + ((color << 16) | (color << 8) | color).toString(16)).slice(-6);";
const char line339[] PROGMEM = "document.querySelector(':root').style.setProperty('--SliderThumbColor', '#' + colorStr);";
const char line340[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.SetColor + \"=\" + (slider.value << 24));";
const char line341[] PROGMEM = "}";
const char line342[] PROGMEM = "";
const char line343[] PROGMEM = "// 2 thumb slider";
const char line344[] PROGMEM = "\"use strict\";";
const char line345[] PROGMEM = "addEventListener('input', e => {";
const char line346[] PROGMEM = "if (e.target.classList.contains(\"twoThumbSlider\"))";
const char line347[] PROGMEM = "{";
const char line348[] PROGMEM = "let _t = e.target;";
const char line349[] PROGMEM = "";
const char line350[] PROGMEM = "_t.parentNode.style.setProperty(`--${_t.id}`, +_t.value);";
const char line351[] PROGMEM = "";
const char line352[] PROGMEM = "SliderTwoThumb_Update();";
const char line353[] PROGMEM = "}";
const char line354[] PROGMEM = "}, false);";
const char line355[] PROGMEM = "";
const char line356[] PROGMEM = "function SliderTwoThumb_Update()";
const char line357[] PROGMEM = "{";
const char line358[] PROGMEM = "var xs = parseInt(getComputedStyle(document.getElementById(\"slider_columen\")).getPropertyValue('--a'), 10);";
const char line359[] PROGMEM = "var xe = parseInt(getComputedStyle(document.getElementById(\"slider_columen\")).getPropertyValue('--b'), 10);";
const char line360[] PROGMEM = "var ys = parseInt(getComputedStyle(document.getElementById(\"slider_row\")).getPropertyValue('--a'), 10);";
const char line361[] PROGMEM = "var ye = parseInt(getComputedStyle(document.getElementById(\"slider_row\")).getPropertyValue('--b'), 10);";
const char line362[] PROGMEM = "";
const char line363[] PROGMEM = "if (xs > xe)";
const char line364[] PROGMEM = "{";
const char line365[] PROGMEM = "var tmp = xs;";
const char line366[] PROGMEM = "xs = xe;";
const char line367[] PROGMEM = "xe = tmp;";
const char line368[] PROGMEM = "}";
const char line369[] PROGMEM = "if (ys > ye)";
const char line370[] PROGMEM = "{";
const char line371[] PROGMEM = "var tmp = ys;";
const char line372[] PROGMEM = "ys = ye;";
const char line373[] PROGMEM = "ye = tmp;";
const char line374[] PROGMEM = "}";
const char line375[] PROGMEM = "";
const char line376[] PROGMEM = "document.getElementById(\"led_column\").innerHTML = (xs + \" - \" + xe);";
const char line377[] PROGMEM = "document.getElementById(\"led_row\").innerHTML = (ys + \" - \" + ye);";
const char line378[] PROGMEM = "SendDataToArduino(\"&\" + XML_RREQUEST.SetArea + \"=X\" + xs + \"-\" + xe + \"Y\" + ys + \"-\" + ye);";
const char line379[] PROGMEM = "}";
const char line380[] PROGMEM = "</script>";
const char line381[] PROGMEM = "";
const char line382[] PROGMEM = "";
const char line383[] PROGMEM = "<style type=\"text/css\">";
const char line384[] PROGMEM = ":root {";
const char line385[] PROGMEM = "--backgroundColor: #222222;";
const char line386[] PROGMEM = "--headerBackgroundColor: #444444;";
const char line387[] PROGMEM = "--BackgroundColorActive: #ffbf00;";
const char line388[] PROGMEM = "--sliderBackgroundColor: #4b4b4b;";
const char line389[] PROGMEM = "--SliderThumbColor: var(--sliderBackgroundColor);";
const char line390[] PROGMEM = "--textColorDark: #000000;";
const char line391[] PROGMEM = "--textColorLight: #ffffff;";
const char line392[] PROGMEM = "--boarderColor: #000000;";
const char line393[] PROGMEM = "";
const char line394[] PROGMEM = "background-color: var(--backgroundColor);";
const char line395[] PROGMEM = "color: var(--textColorLight);";
const char line396[] PROGMEM = "}";
const char line397[] PROGMEM = ".out_box {";
const char line398[] PROGMEM = "float: left;";
const char line399[] PROGMEM = "margin: 0 20px 20px 0;";
const char line400[] PROGMEM = "border: 1px solid blue;";
const char line401[] PROGMEM = "padding: 0 5px 0 5px;";
const char line402[] PROGMEM = "min-width: 280px;";
const char line403[] PROGMEM = "}";
const char line404[] PROGMEM = "input {";
const char line405[] PROGMEM = "margin: 10px;";
const char line406[] PROGMEM = "}";
const char line407[] PROGMEM = "input {";
const char line408[] PROGMEM = "vertical-align: -3px;";
const char line409[] PROGMEM = "}";
const char line410[] PROGMEM = "h1 {";
const char line411[] PROGMEM = "font-size: 150%;";
const char line412[] PROGMEM = "color: var(--textColorLight);";
const char line413[] PROGMEM = "background-color: var(--headerBackgroundColor);";
const char line414[] PROGMEM = "margin: 0 0 10px 0;";
const char line415[] PROGMEM = "width: calc(100% - 32px);";
const char line416[] PROGMEM = "border-radius: 4px;";
const char line417[] PROGMEM = "padding: 8px 16px 8px 16px;";
const char line418[] PROGMEM = "border: 2px solid var(--boarderColor);";
const char line419[] PROGMEM = "}";
const char line420[] PROGMEM = "h2 {";
const char line421[] PROGMEM = "font-size: 120%;";
const char line422[] PROGMEM = "color: var(--textColorLight);";
const char line423[] PROGMEM = "background-color: var(--headerBackgroundColor);";
const char line424[] PROGMEM = "margin: 5px 0 5px 0;";
const char line425[] PROGMEM = "width: calc(100% - 32px);";
const char line426[] PROGMEM = "border-radius: 4px;";
const char line427[] PROGMEM = "padding: 8px 16px 8px 16px;";
const char line428[] PROGMEM = "border: 2px solid var(--boarderColor);";
const char line429[] PROGMEM = "}";
const char line430[] PROGMEM = "p, form, button {";
const char line431[] PROGMEM = "font-size: 80%;";
const char line432[] PROGMEM = "color: var(--textColorDark);";
const char line433[] PROGMEM = "background-color: var(--backgroundColor);";
const char line434[] PROGMEM = "}";
const char line435[] PROGMEM = "a {";
const char line436[] PROGMEM = "color: var(--BackgroundColorActive);";
const char line437[] PROGMEM = "}";
const char line438[] PROGMEM = "";
const char line439[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line440[] PROGMEM = "/* button */";
const char line441[] PROGMEM = ".button {";
const char line442[] PROGMEM = "color: var(--textColorLight);";
const char line443[] PROGMEM = "background-color: var(--backgroundColor);";
const char line444[] PROGMEM = "border: 2px solid var(--headerBackgroundColor);";
const char line445[] PROGMEM = "border-radius: 4px;";
const char line446[] PROGMEM = "padding: 16px 12px;";
const char line447[] PROGMEM = "text-align: center;";
const char line448[] PROGMEM = "text-decoration: none;";
const char line449[] PROGMEM = "display: inline-block;";
const char line450[] PROGMEM = "font-size: 16px;";
const char line451[] PROGMEM = "margin: 4px 2px;";
const char line452[] PROGMEM = "-webkit-transition-duration: 0.4s; /* Safari */";
const char line453[] PROGMEM = "transition-duration: 0.4s;";
const char line454[] PROGMEM = "cursor: pointer;";
const char line455[] PROGMEM = "}";
const char line456[] PROGMEM = "";
const char line457[] PROGMEM = ".button:hover {";
const char line458[] PROGMEM = "background-color: var(--BackgroundColorActive);";
const char line459[] PROGMEM = "color: var(--textColorDark);";
const char line460[] PROGMEM = "}";
const char line461[] PROGMEM = ".button:active {";
const char line462[] PROGMEM = "background-color: var(--BackgroundColorActive);";
const char line463[] PROGMEM = "color: var(--textColorDark);";
const char line464[] PROGMEM = "transform: translateY(2px);";
const char line465[] PROGMEM = "}";
const char line466[] PROGMEM = ".active-class {";
const char line467[] PROGMEM = "background-color: var(--BackgroundColorActive);";
const char line468[] PROGMEM = "color: var(--textColorDark);";
const char line469[] PROGMEM = "}";
const char line470[] PROGMEM = "";
const char line471[] PROGMEM = "/*----------------------------------------------------------------------*/";
const char line472[] PROGMEM = "/* slider */";
const char line473[] PROGMEM = ".slidecontainer {";
const char line474[] PROGMEM = "width: 100%;";
const char line475[] PROGMEM = "}";
const char line476[] PROGMEM = "";
const char line477[] PROGMEM = ".slider {";
const char line478[] PROGMEM = "-webkit-appearance: none;";
const char line479[] PROGMEM = "-moz-appearance: none;";
const char line480[] PROGMEM = "width: calc(100% - 15px);";
const char line481[] PROGMEM = "height: 15px;";
const char line482[] PROGMEM = "border: 1px solid var(--headerBackgroundColor);";
const char line483[] PROGMEM = "border-radius: 5px;";
const char line484[] PROGMEM = "background: var(--BackgroundColorActive);";
const char line485[] PROGMEM = "outline: none;";
const char line486[] PROGMEM = "opacity: 1;";
const char line487[] PROGMEM = "-webkit-transition: .2s;";
const char line488[] PROGMEM = "transition: opacity .2s;";
const char line489[] PROGMEM = "}";
const char line490[] PROGMEM = "";
const char line491[] PROGMEM = ".slider::-webkit-slider-thumb {";
const char line492[] PROGMEM = "-webkit-appearance: none;";
const char line493[] PROGMEM = "-moz-appearance: none;";
const char line494[] PROGMEM = "appearance: none;";
const char line495[] PROGMEM = "width: 25px;";
const char line496[] PROGMEM = "height: 25px;";
const char line497[] PROGMEM = "border-radius: 50%;";
const char line498[] PROGMEM = "background: var(--SliderThumbColor);";
const char line499[] PROGMEM = "cursor: pointer;";
const char line500[] PROGMEM = "}";
const char line501[] PROGMEM = "";
const char line502[] PROGMEM = ".slider::-moz-range-thumb {";
const char line503[] PROGMEM = "width: 25px;";
const char line504[] PROGMEM = "height: 25px;";
const char line505[] PROGMEM = "border-radius: 50%;";
const char line506[] PROGMEM = "background: var(--SliderThumbColor);";
const char line507[] PROGMEM = "cursor: pointer;";
const char line508[] PROGMEM = "}";
const char line509[] PROGMEM = "";
const char line510[] PROGMEM = "";
const char line511[] PROGMEM = "/*---------------------------------------------------------------------*/";
const char line512[] PROGMEM = "/* 2 thumb slider */";
const char line513[] PROGMEM = "#led_slider_row {";
const char line514[] PROGMEM = "width: 150px;";
const char line515[] PROGMEM = "}";
const char line516[] PROGMEM = "";
const char line517[] PROGMEM = "#led_slider_column {";
const char line518[] PROGMEM = "width: calc(100% - 150px);";
const char line519[] PROGMEM = "}";
const char line520[] PROGMEM = "";
const char line521[] PROGMEM = ".wrap {";
const char line522[] PROGMEM = "--dif: calc(var(--max) - var(--min));";
const char line523[] PROGMEM = "display: grid;";
const char line524[] PROGMEM = "grid-template: repeat(2, max-content) 2em/1fr 1fr;";
const char line525[] PROGMEM = "overflow: hidden;";
const char line526[] PROGMEM = "position: relative;";
const char line527[] PROGMEM = "margin: 1em auto;";
const char line528[] PROGMEM = "width: 100%;";
const char line529[] PROGMEM = "background: linear-gradient(0deg, var(--sliderBackgroundColor) 2em, transparent 0);";
const char line530[] PROGMEM = "font-family: ubuntu mono, consolas, monaco, monospace;";
const char line531[] PROGMEM = "}";
const char line532[] PROGMEM = ".wrap::before, .wrap::after {";
const char line533[] PROGMEM = "grid-column: 1/span 2;";
const char line534[] PROGMEM = "grid-row: 3;";
const char line535[] PROGMEM = "height: 100%;";
const char line536[] PROGMEM = "background: var(--BackgroundColorActive);";
const char line537[] PROGMEM = "content: \"\";";
const char line538[] PROGMEM = "}";
const char line539[] PROGMEM = ".wrap::before {";
const char line540[] PROGMEM = "margin-left: calc((var(--a) - var(--min))/var(--dif)*100%);";
const char line541[] PROGMEM = "width: calc((var(--b) - var(--a))/var(--dif)*100%);";
const char line542[] PROGMEM = "}";
const char line543[] PROGMEM = ".wrap::after {";
const char line544[] PROGMEM = "margin-left: calc((var(--b) - var(--min))/var(--dif)*100%);";
const char line545[] PROGMEM = "width: calc((var(--a) - var(--b))/var(--dif)*100%);";
const char line546[] PROGMEM = "}";
const char line547[] PROGMEM = "";
const char line548[] PROGMEM = "[id=multi-lbl] {";
const char line549[] PROGMEM = "grid-column: 1/span 2;";
const char line550[] PROGMEM = "}";
const char line551[] PROGMEM = "";
const char line552[] PROGMEM = ".sr-only {";
const char line553[] PROGMEM = "position: absolute;";
const char line554[] PROGMEM = "clip-path: inset(50%);";
const char line555[] PROGMEM = "}";
const char line556[] PROGMEM = "";
const char line557[] PROGMEM = "input.twoThumbSlider[type=range] {";
const char line558[] PROGMEM = "grid-column: 1/span 2;";
const char line559[] PROGMEM = "grid-row: 3;";
const char line560[] PROGMEM = "z-index: 1;";
const char line561[] PROGMEM = "top: 0;";
const char line562[] PROGMEM = "left: 0;";
const char line563[] PROGMEM = "margin: 0;";
const char line564[] PROGMEM = "background: none;";
const char line565[] PROGMEM = "/* get rid of white Chrome background */";
const char line566[] PROGMEM = "color: #000000;";
const char line567[] PROGMEM = "pointer-events: none;";
const char line568[] PROGMEM = "}";
const char line569[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-runnable-track, input[type=range]::-webkit-slider-thumb, input[type=range] {";
const char line570[] PROGMEM = "-webkit-appearance: none;";
const char line571[] PROGMEM = "}";
const char line572[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-runnable-track {";
const char line573[] PROGMEM = "width: 100%;";
const char line574[] PROGMEM = "height: 100%;";
const char line575[] PROGMEM = "background: none;";
const char line576[] PROGMEM = "}";
const char line577[] PROGMEM = "input.twoThumbSlider[type=range]::-moz-range-track {";
const char line578[] PROGMEM = "width: 100%;";
const char line579[] PROGMEM = "height: 100%;";
const char line580[] PROGMEM = "background: none;";
const char line581[] PROGMEM = "}";
const char line582[] PROGMEM = "input.twoThumbSlider[type=range]::-webkit-slider-thumb {";
const char line583[] PROGMEM = "border: none;";
const char line584[] PROGMEM = "/* get rid of Firefox thumb border */";
const char line585[] PROGMEM = "width: 2em;";
const char line586[] PROGMEM = "height: 100%;";
const char line587[] PROGMEM = "border-radius: 0;";
const char line588[] PROGMEM = "/* get rid of Firefox corner rounding */";
const char line589[] PROGMEM = "background: currentcolor;";
const char line590[] PROGMEM = "pointer-events: auto;";
const char line591[] PROGMEM = "}";
const char line592[] PROGMEM = "input.twoThumbSlider[type=range]::-moz-range-thumb {";
const char line593[] PROGMEM = "border: none;";
const char line594[] PROGMEM = "/* get rid of Firefox thumb border */";
const char line595[] PROGMEM = "width: 2em;";
const char line596[] PROGMEM = "height: 2em;";
const char line597[] PROGMEM = "border-radius: 0;";
const char line598[] PROGMEM = "/* get rid of Firefox corner rounding */";
const char line599[] PROGMEM = "background: currentcolor;";
const char line600[] PROGMEM = "pointer-events: auto;";
const char line601[] PROGMEM = "}";
const char line602[] PROGMEM = "input.twoThumbSlider[type=range]:focus {";
const char line603[] PROGMEM = "z-index: 2;";
const char line604[] PROGMEM = "outline: dotted 1px currentcolor;";
const char line605[] PROGMEM = "}";
const char line606[] PROGMEM = "input.twoThumbSlider[type=range]:focus, input[type=range]:focus + output {";
const char line607[] PROGMEM = "color: darkorange;";
const char line608[] PROGMEM = "}";
const char line609[] PROGMEM = "";
const char line610[] PROGMEM = "output.twoThumbSlider {";
const char line611[] PROGMEM = "grid-row: 2;";
const char line612[] PROGMEM = "}";
const char line613[] PROGMEM = "output.twoThumbSlider:last-child {";
const char line614[] PROGMEM = "text-align: right;";
const char line615[] PROGMEM = "}";
const char line616[] PROGMEM = "output.twoThumbSlider::after {";
const char line617[] PROGMEM = "counter-reset: c var(--c);";
const char line618[] PROGMEM = "content: \"--\" attr(for) \": \" counter(c) \";\";";
const char line619[] PROGMEM = "}";
const char line620[] PROGMEM = "";
const char line621[] PROGMEM = "</style>";
const char line622[] PROGMEM = "</head>";
const char line623[] PROGMEM = "";
const char line624[] PROGMEM = "<body>";
const char line625[] PROGMEM = "<h1>MoBa Licht Steuerung</h1>";
const char line626[] PROGMEM = "<br>";
const char line627[] PROGMEM = "<div id=\"LightScene\"></div>";
const char line628[] PROGMEM = "<br>";
const char line629[] PROGMEM = "<br>";
const char line630[] PROGMEM = "<br>";
const char line631[] PROGMEM = "";
const char line632[] PROGMEM = "<h2>Helligkeit</h2>";
const char line633[] PROGMEM = "<br>";
const char line634[] PROGMEM = "<div class=\"slidecontainer\">";
const char line635[] PROGMEM = "<label for=\"brightness_value\">Helligkeit</label>";
const char line636[] PROGMEM = "<label id=\"brightness_value\"></label>";
const char line637[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"brightness_slider\" oninput=\"BrighntessSliderChanged()\">";
const char line638[] PROGMEM = "</div>";
const char line639[] PROGMEM = "<br>";
const char line640[] PROGMEM = "<br>";
const char line641[] PROGMEM = "";
const char line642[] PROGMEM = "<h2>Farbe</h2>";
const char line643[] PROGMEM = "<br>";
const char line644[] PROGMEM = "<div class=\"slidecontainer\">";
const char line645[] PROGMEM = "<label for=\"color_rgb_value\">RGB</label>";
const char line646[] PROGMEM = "<label id=\"color_rgb_value\"></label>";
const char line647[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"1535\" value=\"50\" class=\"slider\" id=\"color_rgb_slider\" oninput=\"ColorRGBSliderChanged()\" style=\"background-image: linear-gradient(90deg, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff, #ff0000);\">";
const char line648[] PROGMEM = "</div>";
const char line649[] PROGMEM = "<br>";
const char line650[] PROGMEM = "<div class=\"slidecontainer\">";
const char line651[] PROGMEM = "<label for=\"color_red_value\">Rot</label>";
const char line652[] PROGMEM = "<label id=\"color_red_value\"></label>";
const char line653[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_red_slider\" oninput=\"ColorRGBSingleSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, red)\">";
const char line654[] PROGMEM = "";
const char line655[] PROGMEM = "<label for=\"color_green_value\">Gr&uuml;n</label>";
const char line656[] PROGMEM = "<label id=\"color_green_value\"></label>";
const char line657[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_green_slider\" oninput=\"ColorRGBSingleSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, rgb(0, 255, 0))\">";
const char line658[] PROGMEM = "";
const char line659[] PROGMEM = "<label for=\"color_blue_value\">Blau</label>";
const char line660[] PROGMEM = "<label id=\"color_blue_value\"></label>";
const char line661[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_blue_slider\" oninput=\"ColorRGBSingleSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, blue)\">";
const char line662[] PROGMEM = "";
const char line663[] PROGMEM = "<label for=\"color_white_value\">Weiss</label>";
const char line664[] PROGMEM = "<label id=\"color_white_value\"></label>";
const char line665[] PROGMEM = "<input type=\"range\" min=\"0\" max=\"255\" value=\"50\" class=\"slider\" id=\"color_white_slider\" oninput=\"ColorWhiteSliderChanged()\" style=\"background-image: linear-gradient(90deg, black, white)\">";
const char line666[] PROGMEM = "</div>";
const char line667[] PROGMEM = "<br>";
const char line668[] PROGMEM = "<br>";
const char line669[] PROGMEM = "";
const char line670[] PROGMEM = "<h2>Leuchtposition</h2>";
const char line671[] PROGMEM = "<table style=\"width: 100%\">";
const char line672[] PROGMEM = "<tr>";
const char line673[] PROGMEM = "<td>";
const char line674[] PROGMEM = "<label for=\"led_row\">Reihen</label>";
const char line675[] PROGMEM = "<label type=\"text\" id=\"led_row\" readonly style=\"border:0; color:#f6931f; font-weight:bold;\"></label>";
const char line676[] PROGMEM = "</td>";
const char line677[] PROGMEM = "<td>";
const char line678[] PROGMEM = "<label for=\"led_column\">L&auml;nge</label>";
const char line679[] PROGMEM = "<label type=\"text\" id=\"led_column\" readonly style=\"border:0; color:#f6931f; font-weight:bold;\"></label>";
const char line680[] PROGMEM = "</td>";
const char line681[] PROGMEM = "</tr>";
const char line682[] PROGMEM = "<tr>";
const char line683[] PROGMEM = "<td id=\"led_slider_row\">";
const char line684[] PROGMEM = "<!--<div style=\"transform: rotate(270deg);\">-->";
const char line685[] PROGMEM = "<div>";
const char line686[] PROGMEM = "<div id=\"slider_row\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: 0; --b: 3; --min: 0; --max: 3;\">";
const char line687[] PROGMEM = "<!--<div id=\"multi-lbl\">Multi thumb slider: 0 - 15</div>-->";
const char line688[] PROGMEM = "<input id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"0\" max=\"3\" />";
const char line689[] PROGMEM = "<!--<output for=\"a\" style=\"--c: var(--a)\"></output>-->";
const char line690[] PROGMEM = "<input id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"3\" max=\"3\" />";
const char line691[] PROGMEM = "<!--<output for=\"b\" style=\"--c: var(--b)\"></output>-->";
const char line692[] PROGMEM = "</div>";
const char line693[] PROGMEM = "</td>";
const char line694[] PROGMEM = "<td id=led_slider_column>";
const char line695[] PROGMEM = "<div id=\"slider_columen\" class=\"wrap\" role=\"group\" aria-labelledby=\"multi-lbl\" style=\"--a: 20; --b: 120; --min: 0; --max: 284\">";
const char line696[] PROGMEM = "<!--<div id=\"multi-lbl\">Multi thumb slider: 0 - 15</div>-->";
const char line697[] PROGMEM = "<input id=\"a\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"20\" max=\"284\" />";
const char line698[] PROGMEM = "<!--<output for=\"a\" style=\"--c: var(--a)\"></output>-->";
const char line699[] PROGMEM = "<input id=\"b\" class=\"twoThumbSlider\" type=\"range\" min=\"0\" value=\"120\" max=\"284\" />";
const char line700[] PROGMEM = "<!--<output for=\"b\" style=\"--c: var(--b)\"></output>-->";
const char line701[] PROGMEM = "</div>";
const char line702[] PROGMEM = "</td>";
const char line703[] PROGMEM = "</tr>";
const char line704[] PROGMEM = "</table>";
const char line705[] PROGMEM = "</body>";
const char line706[] PROGMEM = "</html>";
const char line707[] PROGMEM = "<html>";
const char line708[] PROGMEM = "<footer>";
const char line709[] PROGMEM = "<div>";
const char line710[] PROGMEM = "<br>";
const char line711[] PROGMEM = "<br>";
const char line712[] PROGMEM = "<hr>";
const char line713[] PROGMEM = "07. November 2022 &nbsp; &copy; MarkusNTrains";
const char line714[] PROGMEM = "<a href='mailto:markusntrains@gmx.ch'>E-Mail</a>";
const char line715[] PROGMEM = "</div>";
const char line716[] PROGMEM = "</footer>";
const char line717[] PROGMEM = "</html>";

const char* const website_a[] PROGMEM = {line1, line2, line3, line4, line5, line6, line7, line8, line9, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, line21, line22, line23, line24, line25, line26, line27, line28, line29, line30, line31, line32, line33, line34, line35, line36, line37, line38, line39, line40, line41, line42, line43, line44, line45, line46, line47, line48, line49, line50, line51, line52, line53, line54, line55, line56, line57, line58, line59, line60, line61, line62, line63, line64, line65, line66, line67, line68, line69, line70, line71, line72, line73, line74, line75, line76, line77, line78, line79, line80, line81, line82, line83, line84, line85, line86, line87, line88, line89, line90, line91, line92, line93, line94, line95, line96, line97, line98, line99, line100, line101, line102, line103, line104, line105, line106, line107, line108, line109, line110, line111, line112, line113, line114, line115, line116, line117, line118, line119, line120, line121, line122, line123, line124, line125, line126, line127, line128, line129, line130, line131, line132, line133, line134, line135, line136, line137, line138, line139, line140, line141, line142, line143, line144, line145, line146, line147, line148, line149, line150, line151, line152, line153, line154, line155, line156, line157, line158, line159, line160, line161, line162, line163, line164, line165, line166, line167, line168, line169, line170, line171, line172, line173, line174, line175, line176, line177, line178, line179, line180, line181, line182, line183, line184, line185, line186, line187, line188, line189, line190, line191, line192, line193, line194, line195, line196, line197, line198, line199, line200, line201, line202, line203, line204, line205, line206, line207, line208, line209, line210, line211, line212, line213, line214, line215, line216, line217, line218, line219, line220, line221, line222, line223, line224, line225, line226, line227, line228, line229, line230, line231, line232, line233, line234, line235, line236, line237, line238, line239, line240, line241, line242, line243, line244, line245, line246, line247, line248, line249, line250, line251, line252, line253, line254, line255, line256, line257, line258, line259, line260, line261, line262, line263, line264, line265, line266, line267, line268, line269, line270, line271, line272, line273, line274, line275, line276, line277, line278, line279, line280, line281, line282, line283, line284, line285, line286, line287, line288, line289, line290, line291, line292, line293, line294, line295, line296, line297, line298, line299, line300, line301, line302, line303, line304, line305, line306, line307, line308, line309, line310, line311, line312, line313, line314, line315, line316, line317, line318, line319, line320, line321, line322, line323, line324, line325, line326, line327, line328, line329, line330, line331, line332, line333, line334, line335, line336, line337, line338, line339, line340, line341, line342, line343, line344, line345, line346, line347, line348, line349, line350, line351, line352, line353, line354, line355, line356, line357, line358, line359, line360, line361, line362, line363, line364, line365, line366, line367, line368, line369, line370, line371, line372, line373, line374, line375, line376, line377, line378, line379, line380, line381, line382, line383, line384, line385, line386, line387, line388, line389, line390, line391, line392, line393, line394, line395, line396, line397, line398, line399, line400, line401, line402, line403, line404, line405, line406, line407, line408, line409, line410, line411, line412, line413, line414, line415, line416, line417, line418, line419, line420, line421, line422, line423, line424, line425, line426, line427, line428, line429, line430, line431, line432, line433, line434, line435, line436, line437, line438, line439, line440, line441, line442, line443, line444, line445, line446, line447, line448, line449, line450, line451, line452, line453, line454, line455, line456, line457, line458, line459, line460, line461, line462, line463, line464, line465, line466, line467, line468, line469, line470, line471, line472, line473, line474, line475, line476, line477, line478, line479, line480, line481, line482, line483, line484, line485, line486, line487, line488, line489, line490, line491, line492, line493, line494, line495, line496, line497, line498, line499, line500, line501, line502, line503, line504, line505, line506, line507, line508, line509, line510, line511, line512, line513, line514, line515, line516, line517, line518, line519, line520, line521, line522, line523, line524, line525, line526, line527, line528, line529, line530, line531, line532, line533, line534, line535, line536, line537, line538, line539, line540, line541, line542, line543, line544, line545, line546, line547, line548, line549, line550, line551, line552, line553, line554, line555, line556, line557, line558, line559, line560, line561, line562, line563, line564, line565, line566, line567, line568, line569, line570, line571, line572, line573, line574, line575, line576, line577, line578, line579, line580, line581, line582, line583, line584, line585, line586, line587, line588, line589, line590, line591, line592, line593, line594, line595, line596, line597, line598, line599, line600, line601, line602, line603, line604, line605, line606, line607, line608, line609, line610, line611, line612, line613, line614, line615, line616, line617, line618, line619, line620, line621, line622, line623, line624, line625, line626, line627, line628, line629, line630, line631, line632, line633, line634, line635, line636, line637, line638, line639, line640, line641, line642, line643, line644, line645, line646, line647, line648, line649, line650, line651, line652, line653, line654, line655, line656, line657, line658, line659, line660, line661, line662, line663, line664, line665, line666, line667, line668, line669, line670, line671, line672, line673, line674, line675, line676, line677, line678, line679, line680, line681, line682, line683, line684, line685, line686, line687, line688, line689, line690, line691, line692, line693, line694, line695, line696, line697, line698, line699, line700, line701, line702, line703, line704, line705, line706, line707, line708, line709, line710, line711, line712, line713, line714, line715, line716, line717};


//-----------------------------------------------------------------------------
// define
#define WEBSITE_NOF_LINES 717


//-----------------------------------------------------------------------------
// static module variable



//*****************************************************************************
// description:
//   Website_SendToClient
//*****************************************************************************
void Website_SendToClient(EthernetClient* client)
{
	uint32_t line = 0;
    char line_str[253];

	for (line = 0; line < WEBSITE_NOF_LINES; line++)
	{
        strcpy_P(line_str, (char*)pgm_read_word(&(website_a[line])));
		client->println(line_str);
	}
}
